## heyzap

Enable the https://www.heyzap.com/[Heyzap advertisements]. Use https://castle-engine.io/apidoc/html/CastleAds.TAds.html[TAds] class from the https://castle-engine.io/apidoc/html/CastleAds.html[CastleAds] unit to show and control the ads from your Pascal code, with `AdNetwork` set to `anHeyzap`.

Requires:

* The core of this service is a closed-source library distributed in Heyzap SDK.
 ** Download the SDK from https://developers.heyzap.com/docs/android_sdk_setup_and_requirements (select in _Step 1_ whether you want to use beta or not, and then in _Step 2. Download the SDK_ click on SDK link).
 ** Unzip the SDK to a temporary location.
 ** Copy the jar file from SDK `android-sdk/heyzap-ads-sdk.jar` into `castle_game_engine/tools/build-tool/data/android/integrated-services/heyzap/app/libs/heyzap-ads-sdk.jar`.

_Optional notes to use Heyzap mediation:_ You can use Heyzap integration (SDK) to get ads from _many_ ad networks -- not only from Heyzap own network, but also from AdMob, Chartboost and many more. To do this, you will need to setup the integration in your Heyzap dashboard. Also you will need to follow the instructions on https://developers.heyzap.com/docs/android_sdk_setup_and_requirements to add additional networks SDKs. Select the additional networks on that page, and follow the instructions:

* Usually, Heyzap docs will instruct you to download some additional SDK. Do as it says, and place the `.jar` and `.aar` files into the `+..../integrated-services/heyzap/app/libs/+` directory, alongside the Heyzap jar.
* For every `.aar` file that you have added, add appropriate <dependency> line to the `+..../integrated-services/heyzap/app/build.gradle+` file. Like this:
+
[,xml]
----
<dependency>implementation(name:'AudienceNetwork', ext:'aar')</dependency>
<dependency>implementation(name:'unity-ads', ext:'aar')</dependency>
----

* Make the necessary modifications in the `+..../integrated-services/heyzap/app/src/main/AndroidManifest.xml+`. Make sure it contains only (and exactly!) the activities/permissions that Heyzap docs show you.
* _Note for AdMob_: Using AdMob requires that you also use `"google_play_services"` service. And you should add to the `+..../integrated-services/heyzap/app/build.gradle+` file these lines:
+
[,xml]
----
<dependency>implementation 'com.google.android.gms:play-services-ads:9.4.0'</dependency>
<dependency>implementation 'com.google.android.gms:play-services-location:9.4.0'</dependency>
----

* NOTE: that some ads SDK may require increasing the `min_sdk_version` in your link:pass:[CastleEngineManifest.xml examples][CastleEngineManifest.xml]. You will get a clear error message when building APK in case this is necessary. Currently, _Facebook Ads (Facebook Audience Network)_ requires min SDK >= 11.
* NOTE: when you use Heyzap to integrate with some 3rd-party ad network (for example with Chartboost), then you _should not_ add a service in `CastleEngineManifest.xml` to also directly interact with this network (in this example "chartboost"). That is: _include *only* the heyzap service in CastleEngineManifest.xml_. Otherwise the SDK underneath (like chartboost) will be initialized and handled by two code paths (one directly in our Java code, and one inside Heyzap jar), which can lead to various troubles.
* To test your integration, call `TAds.StartTestActivity(anHeyzap)` in your Pascal code. This will show a special activity where you can test whether the connection with your 3rd-party networks works OK. Optional, but highly suggested!
