default:
	@echo 'No default target in this Makefile'

# Simple install.
# You may as well symlink to /usr/local/share/rift, for system-wide install.
install:
	rm -f $(HOME)/.rift.data
	ln -s $(shell pwd) $(HOME)/.rift.data
