{
  Copyright 2025-2025 Michalis Kamburelis.

  This file is part of "Castle Game Engine".

  "Castle Game Engine" is free software; see the file COPYING.txt,
  included in this distribution, for details about the copyright.

  "Castle Game Engine" is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

  ----------------------------------------------------------------------------
}
{ Generate Pascal code IFC API. See README.md for details. }

{$I castleconf.inc}

uses SysUtils, Classes, Dom, XmlRead, Generics.Defaults, Generics.Collections,
  CastleHttps, // support HTTPS
  CastleStringUtils, CastleClassUtils, CastleDownload, CastleXmlUtils,
  CastleUtils, CastleFilesUtils;

const
  SchemaUrl = 'https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/IFC4X3_ADD2.xsd';
  SchemaFile = 'IFC4X3_ADD2.xsd';
  ManuallyDefinedTypesUnit = '../../../src/scene/load/ifc/castleifc_ifc_standard_types.inc';
  OutputPath: String = '../../../src/scene/load/ifc/castleifc_ifc_standard_types_autogenerated.inc';
var
  ManuallyDefinedTypes: String;

{ Simple type resolution ---------------------------------------------------- }

type
  TStringStringDictionary = {$ifdef FPC}specialize{$endif} TDictionary<String, String>;
var
  { Maps IFC simple type name (without ifc: prefix) to raw XSD base type.
    Built during first pass over XSD xs:simpleType elements. }
  SimpleTypeRawBase: TStringStringDictionary;

  { Set of IFC type names that are enums (have xs:enumeration). }
  SimpleTypeEnumNames: TStringList;

  { Cache: IFC simple type name -> resolved Pascal type name.
    Built lazily by ResolveSimpleType. }
  SimpleTypePascalCache: TStringStringDictionary;

{ Map XSD built-in types to Pascal types. Returns '' if not recognized. }
function XsdBaseTypeToPascal(const XsdType: String): String;
begin
  if (XsdType = 'xs:double') then
    Result := 'Single'
  else if (XsdType = 'xs:long') or (XsdType = 'xs:integer') then
    Result := 'Integer'
  else if (XsdType = 'xs:boolean') then
    Result := 'Boolean'
  else if (XsdType = 'xs:normalizedString') or (XsdType = 'xs:string') then
    Result := 'String'
  else if (XsdType = 'xs:hexBinary') or (XsdType = 'xs:base64Binary') or
          (XsdType = 'xs:anyURI') then
    Result := 'String'
  else if XsdType = 'ifc:logical' then
    Result := 'Boolean'
  else
    Result := '';
end;

{ Resolve an IFC type name (possibly with ifc: prefix) to a Pascal type.
  Returns the resolved Pascal type name, or '' if the type is not a simple type
  (i.e. it is a complex type / class). }
function ResolveSimpleType(const IfcTypeName: String): String;
var
  CleanName, RawBase: String;
begin
  { Handle XSD built-in types }
  Result := XsdBaseTypeToPascal(IfcTypeName);
  if Result <> '' then Exit;

  CleanName := PrefixRemove('ifc:', IfcTypeName, true);

  { Check cache }
  if SimpleTypePascalCache.TryGetValue(CleanName, Result) then
    Exit;

  { Check if it is a known simple type }
  if SimpleTypeRawBase.TryGetValue(CleanName, RawBase) then
  begin
    { Enum types resolve to their Pascal enum type name }
    if SimpleTypeEnumNames.IndexOf(CleanName) >= 0 then
      Result := 'T' + CleanName
    else
      { Scalar type - resolve base recursively }
      Result := ResolveSimpleType(RawBase);

    if Result <> '' then
      SimpleTypePascalCache.AddOrSetValue(CleanName, Result);
    Exit;
  end;

  Result := ''; { not a simple type }
end;

{ Check if TypeName is fully defined in the manually-written
  castleifc_ifc_standard_types.inc (not just a forward declaration). }
function IsManuallyDefined(const TypeName: String): Boolean;
var
  SearchStr: String;
begin
  SearchStr := '  ' + TypeName + ' = ';
  { Must have some definition }
  if Pos(SearchStr, ManuallyDefinedTypes) = 0 then
    Exit(False);
  { If only a forward declaration (= class;) exists, it is NOT fully defined.
    A forward declaration means the full definition is in the autogenerated file. }
  if Pos(SearchStr + 'class;', ManuallyDefinedTypes) <> 0 then
  begin
    { It has a forward declaration. Check if there is also a full definition. }
    Result :=
      (Pos(SearchStr + 'class(', ManuallyDefinedTypes) <> 0) or
      (Pos(SearchStr + 'class abstract(', ManuallyDefinedTypes) <> 0);
  end else
    Result := True; { has a definition that is not a forward declaration }
end;

{ Escape Pascal reserved words used as property names. }
function PascalPropertyName(const AName: String): String;
begin
  if SameText(AName, 'Type') or
     SameText(AName, 'Operator') or
     SameText(AName, 'Label') or
     SameText(AName, 'String') or
     SameText(AName, 'Set') or
     SameText(AName, 'File') or
     SameText(AName, 'Unit') or
     SameText(AName, 'Object') or
     SameText(AName, 'Class') or
     SameText(AName, 'Property') or
     SameText(AName, 'Array') or
     SameText(AName, 'In') or
     SameText(AName, 'Out') or
     SameText(AName, 'Result') or
     SameText(AName, 'Self') or
     SameText(AName, 'To') or
     SameText(AName, 'Of') or
     SameText(AName, 'Index') or
     SameText(AName, 'Name') or
     SameText(AName, 'Destroy') or
     SameText(AName, 'Create') then
    Result := '&' + AName
  else
    Result := AName;
end;

{ Convert an XSD enum value to PascalCase identifier.
  E.g. 'boom_barrier' -> 'Boom_Barrier', 'notdefined' -> 'Notdefined'. }
function EnumValueToPascal(const Value: String): String;
var
  I: Integer;
  CapNext: Boolean;
begin
  Result := Value;
  if Result = '' then Exit;

  { Capitalize first letter }
  Result[1] := UpCase(Result[1]);

  { Capitalize letter after each underscore }
  CapNext := False;
  for I := 2 to Length(Result) do
  begin
    if Result[I] = '_' then
      CapNext := True
    else if CapNext then
    begin
      Result[I] := UpCase(Result[I]);
      CapNext := False;
    end;
  end;
end;

{ TIfcType ------------------------------------------------------------------ }

type
  TIfcType = class
    NameIfc, NamePascal: String;
    function DeclareOrder: Integer; virtual;
    class function IfcNameToPascal(const IfcClassName: String): String; static;
    procedure MakeOutput(var OutputInterface, OutputImplementation,
      OutputAddClasses: String); virtual;
  end;

function TIfcType.DeclareOrder: Integer;
begin
  Result := 0;
end;

class function TIfcType.IfcNameToPascal(const IfcClassName: String): String; static;
begin
  if SameText(IfcClassName, 'ifc:Entity') then
    Result := 'IfcPersistent' // base ancestor of all IFC classes
  else
    Result := PrefixRemove('Ifc:', IfcClassName, true);
  { Convert XSD -temp to _Temp (valid Pascal).
    XSD is using this for some intermediate classes, not in spec, but useful
    to define. We follow this in Pascal. }
  if IsSuffix('-temp', Result, true) then
    Result := SuffixRemove('-temp', Result, true) + '_Temp';
  { Follow conventions of src/scene/load/ifc/castleifc_ifc_standard_types.inc
    to name IFC classes.
    Add _Spec suffix to classes that would otherwise seems like TObjectList
    descendants. }
  if IsSuffix('List', Result, true) then
    Result := Result + '_Spec';
  Result := 'T' + Result;
end;

procedure TIfcType.MakeOutput(var OutputInterface, OutputImplementation,
  OutputAddClasses: String);
begin
  // nothing to do here
end;

{ TIfcEnumType -------------------------------------------------------------- }

type
  TIfcEnumType = class(TIfcType)
    Values: TStringList;
    constructor Create;
    destructor Destroy; override;
    function DeclareOrder: Integer; override;
    procedure MakeOutput(var OutputInterface, OutputImplementation,
      OutputAddClasses: String); override;
  end;

constructor TIfcEnumType.Create;
begin
  inherited;
  Values := TStringList.Create;
end;

destructor TIfcEnumType.Destroy;
begin
  FreeAndNil(Values);
  inherited;
end;

function TIfcEnumType.DeclareOrder: Integer;
begin
  Result := 0; { enums before classes }
end;

procedure TIfcEnumType.MakeOutput(var OutputInterface, OutputImplementation,
  OutputAddClasses: String);
var
  I, NotDefinedIdx, UserDefinedIdx: Integer;
  V: String;
begin
  inherited;

  if Values.Count = 0 then Exit;

  { Reorder: place 'notdefined' or 'userdefined' first (as default value).
    Convention from manual code: default enum value should be first. }
  NotDefinedIdx := -1;
  UserDefinedIdx := -1;
  for I := 0 to Values.Count - 1 do
  begin
    if SameText(Values[I], 'notdefined') then
      NotDefinedIdx := I;
    if SameText(Values[I], 'userdefined') then
      UserDefinedIdx := I;
  end;

  { Move notdefined first, then userdefined second }
  if NotDefinedIdx >= 0 then
  begin
    Values.Move(NotDefinedIdx, 0);
    { Adjust userDefinedIdx if it shifted }
    if (UserDefinedIdx >= 0) then
    begin
      if UserDefinedIdx < NotDefinedIdx then
        Inc(UserDefinedIdx)
      else if UserDefinedIdx > 0 then
        { already correct, notdefined moved before it };
      { Find it again to be safe }
      UserDefinedIdx := -1;
      for I := 0 to Values.Count - 1 do
        if SameText(Values[I], 'userdefined') then
        begin
          UserDefinedIdx := I;
          Break;
        end;
      if (UserDefinedIdx > 1) then
        Values.Move(UserDefinedIdx, 1);
    end;
  end else
  if UserDefinedIdx >= 0 then
    Values.Move(UserDefinedIdx, 0);

  OutputInterface := OutputInterface +
    '  ' + NamePascal + ' = (' + NL;
  for I := 0 to Values.Count - 1 do
  begin
    V := EnumValueToPascal(Values[I]);
    OutputInterface := OutputInterface + '    ' + V;
    if I < Values.Count - 1 then
      OutputInterface := OutputInterface + ',';
    OutputInterface := OutputInterface + NL;
  end;
  OutputInterface := OutputInterface +
    '  );' + NL + NL;
end;

{ TIfcPropertyKind, TIfcProperty -------------------------------------------- }

type
  TIfcPropertyKind = (
    pkString,    { String property }
    pkFloat,     { Single property }
    pkInteger,   { Integer property }
    pkBoolean,   { Boolean property }
    pkEnum,      { Enum type property }
    pkReference, { Reference to another IFC class }
    pkList       { List of IFC class instances }
  );

  TIfcProperty = class
    NameIfc: String;     { Name from XSD }
    NamePascal: String;  { Pascal property name (may have & prefix) }
    Kind: TIfcPropertyKind;
    TypePascal: String;  { Pascal type for the property / list type }
    ListItemTypePascal: String; { For pkList: the item type }
  end;

  TIfcPropertyList = {$ifdef FPC}specialize{$endif} TObjectList<TIfcProperty>;

{ TIfcComplexType ----------------------------------------------------------- }

type
  TIfcComplexType = class(TIfcType)
    BaseIfc, BasePascal: String;
    BaseInstance: TIfcComplexType;
    Abstract: Boolean;
    Properties: TIfcPropertyList;
    IsExtension: Boolean; { true = xs:extension, false = xs:restriction }
    constructor Create;
    destructor Destroy; override;
    function DeclareOrder: Integer; override;
    function HasListProperties: Boolean;
    procedure MakeOutput(var OutputInterface, OutputImplementation,
      OutputAddClasses: String); override;
  end;

constructor TIfcComplexType.Create;
begin
  inherited;
  Properties := TIfcPropertyList.Create(true);
  IsExtension := True;
end;

destructor TIfcComplexType.Destroy;
begin
  FreeAndNil(Properties);
  inherited;
end;

function TIfcComplexType.DeclareOrder: Integer;
begin
  Result := inherited;
  Inc(Result); // place all classes after simple types like enums
  { This is a recursive call, but shouldn't hang if there are no cycles
    in ancestry tree in XSD. }
  if BaseInstance <> nil then
    Result := Result + 1 + BaseInstance.DeclareOrder;
end;

function TIfcComplexType.HasListProperties: Boolean;
var
  I: Integer;
begin
  for I := 0 to Properties.Count - 1 do
    if Properties[I].Kind = pkList then
      Exit(True);
  Result := False;
end;

procedure TIfcComplexType.MakeOutput(var OutputInterface, OutputImplementation,
  OutputAddClasses: String);
const
  IfcSpecUrl = 'https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/%s.htm';
var
  NiceNameIfc, Comment: String;
  I: Integer;
  Prop: TIfcProperty;
  HasLists: Boolean;
  FieldDecls, PropDecls, CtorBody, DtorBody: String;
begin
  inherited;

  NiceNameIfc := PrefixRemove('Ifc:', NameIfc, true);
  if IsSuffix('_Temp', NamePascal, true) then
  begin
    Comment := Format('{ IFC internal class %s (not in specification, only in XSD). }', [
      NiceNameIfc
    ]);
  end else
  begin
    Comment := Format('{ IFC class @url(' + IfcSpecUrl + ' %s). }', [
      NiceNameIfc,
      NiceNameIfc
    ]);
  end;

  { Build field declarations, property declarations, constructor/destructor bodies }
  FieldDecls := '';
  PropDecls := '';
  CtorBody := '';
  DtorBody := '';
  HasLists := False;

  for I := 0 to Properties.Count - 1 do
  begin
    Prop := Properties[I];
    FieldDecls := FieldDecls + Format('    F%s: %s;' + NL, [
      Prop.NameIfc, Prop.TypePascal
    ]);

    case Prop.Kind of
      pkList:
        begin
          HasLists := True;
          { List properties are read-only }
          PropDecls := PropDecls + Format('    property %s: %s read F%s;' + NL, [
            Prop.NamePascal, Prop.TypePascal, Prop.NameIfc
          ]);
          CtorBody := CtorBody + Format(
            '  F%s := %s.Create(false);' + NL, [
            Prop.NameIfc, Prop.TypePascal
          ]);
          DtorBody := DtorBody + Format(
            '  FreeAndNil(F%s);' + NL, [
            Prop.NameIfc
          ]);
        end;
      else
        begin
          { Scalar and reference properties are read-write }
          PropDecls := PropDecls + Format('    property %s: %s read F%s write F%s', [
            Prop.NamePascal, Prop.TypePascal, Prop.NameIfc, Prop.NameIfc
          ]);
          { Add default clause for booleans }
          if Prop.Kind = pkBoolean then
            PropDecls := PropDecls + ' default false';
          PropDecls := PropDecls + ';' + NL;
        end;
    end;
  end;

  { Generate class interface }
  OutputInterface := OutputInterface + Format(
    '  %s' + NL +
    '  %s = class%s(%s)' + NL +
    '  strict private' + NL, [
      Comment,
      NamePascal,
      Iff(Abstract, ' abstract', ''),
      BasePascal
    ]);

  OutputInterface := OutputInterface + FieldDecls;

  if HasLists then
  begin
    OutputInterface := OutputInterface +
      '  public' + NL +
      '    constructor Create(AOwner: TComponent); override;' + NL +
      '    destructor Destroy; override;' + NL;
  end;

  if PropDecls <> '' then
    OutputInterface := OutputInterface +
      '  published' + NL + PropDecls;

  OutputInterface := OutputInterface +
    '  end;' + NL + NL;

  { Generate constructor/destructor implementation }
  if HasLists then
  begin
    OutputImplementation := OutputImplementation +
      'constructor ' + NamePascal + '.Create(AOwner: TComponent);' + NL +
      'begin' + NL +
      '  inherited;' + NL +
      CtorBody +
      'end;' + NL + NL;

    OutputImplementation := OutputImplementation +
      'destructor ' + NamePascal + '.Destroy;' + NL +
      'begin' + NL +
      DtorBody +
      '  inherited;' + NL +
      'end;' + NL + NL;
  end;

  OutputAddClasses := OutputAddClasses + Format(
    '  FIfcClasses.Add(%s);' + NL, [
      NamePascal
    ]);
end;

{ TIfcTypeList -------------------------------------------------------------- }

type
  TIfcTypeList = class({$ifdef FPC}specialize{$endif} TObjectList<TIfcType>)
  public
    { @nil if not found. }
    function Find(const NamePascal: String): TIfcType;
    { Assign TIfcComplexType.BaseInstance where possible. }
    procedure ResolveAncestors;
    { Compare TIfcType to determine order in which they should be declared. }
    function CompareIfcTypes(
      {$ifdef GENERICS_CONSTREF}constref{$else}const{$endif}
      Left, Right: TIfcType): Integer;
    procedure MakeOutput(out OutputInterface, OutputImplementation,
      OutputAddClasses: String);
  end;

  TIfcTypeComparer = specialize TComparer<TIfcType>;

var
  IfcTypes: TIfcTypeList;

function TIfcTypeList.Find(const NamePascal: String): TIfcType;
begin
  for Result in Self do
    if Result.NamePascal = NamePascal then
      Exit;
  Result := nil;
end;

procedure TIfcTypeList.ResolveAncestors;
var
  IfcType: TIfcType;
  ComplexType: TIfcComplexType;
begin
  for IfcType in Self do
    if IfcType is TIfcComplexType then
    begin
      ComplexType := TIfcComplexType(IfcType);
      ComplexType.BaseInstance := Find(ComplexType.BasePascal) as TIfcComplexType;
    end;
end;

function TIfcTypeList.CompareIfcTypes(
  {$ifdef GENERICS_CONSTREF}constref{$else}const{$endif}
  Left, Right: TIfcType): Integer;
begin
  Result := Left.DeclareOrder - Right.DeclareOrder;
  if Result = 0 then
    Result := CompareStr(Left.NamePascal, Right.NamePascal);
end;

procedure TIfcTypeList.MakeOutput(out OutputInterface, OutputImplementation,
  OutputAddClasses: String);
var
  IfcType: TIfcType;
  ComplexType: TIfcComplexType;
  Prop: TIfcProperty;
  I, J: Integer;
  OutputForwardDecls, OutputListForwardDecls, OutputEnums,
    OutputClasses, OutputListDefs: String;
  ListTypeName, ItemTypeName: String;
  NeededListTypes: TStringList; { Name=Value pairs: ListTypeName=ItemTypeName }
begin
  OutputForwardDecls := '';
  OutputListForwardDecls := '';
  OutputEnums := '';
  OutputClasses := '';
  OutputListDefs := '';
  OutputImplementation := '';
  OutputAddClasses := '';

  NeededListTypes := TStringList.Create;
  try
    { 1. Forward declarations for all auto-generated complex types }
    for IfcType in Self do
      if IfcType is TIfcComplexType then
        OutputForwardDecls := OutputForwardDecls +
          '  ' + IfcType.NamePascal + ' = class;' + NL;

    { 2. Collect all list types needed by auto-generated class properties }
    for IfcType in Self do
      if IfcType is TIfcComplexType then
      begin
        ComplexType := TIfcComplexType(IfcType);
        for J := 0 to ComplexType.Properties.Count - 1 do
        begin
          Prop := ComplexType.Properties[J];
          if Prop.Kind = pkList then
            if not IsManuallyDefined(Prop.TypePascal) then
              if NeededListTypes.IndexOfName(Prop.TypePascal) < 0 then
                NeededListTypes.Add(Prop.TypePascal + '=' + Prop.ListItemTypePascal);
        end;
      end;

    { 3. Forward declarations for auto-generated list types }
    for I := 0 to NeededListTypes.Count - 1 do
    begin
      ListTypeName := NeededListTypes.Names[I];
      OutputListForwardDecls := OutputListForwardDecls +
        '  ' + ListTypeName + ' = class;' + NL;
    end;

    { 4. Enum types }
    for IfcType in Self do
      if IfcType is TIfcEnumType then
        TIfcEnumType(IfcType).MakeOutput(OutputEnums, OutputImplementation, OutputAddClasses);

    { 5. Full class definitions }
    for IfcType in Self do
      if IfcType is TIfcComplexType then
        TIfcComplexType(IfcType).MakeOutput(OutputClasses, OutputImplementation, OutputAddClasses);

    { 6. Full list type definitions (after all classes, so item types are known) }
    for I := 0 to NeededListTypes.Count - 1 do
    begin
      ListTypeName := NeededListTypes.Names[I];
      ItemTypeName := NeededListTypes.ValueFromIndex[I];
      OutputListDefs := OutputListDefs + Format(
        '  %s = class({$ifdef FPC}specialize{$endif} TObjectList<%s>)' + NL +
        '  end;' + NL + NL, [
          ListTypeName, ItemTypeName
        ]);
    end;
  finally
    FreeAndNil(NeededListTypes);
  end;

  { Combine all sections in correct dependency order }
  OutputInterface := '';

  if OutputForwardDecls <> '' then
    OutputInterface := OutputInterface +
      '  { Forward declarations for auto-generated IFC classes. }' + NL +
      OutputForwardDecls + NL;

  if OutputListForwardDecls <> '' then
    OutputInterface := OutputInterface +
      '  { Forward declarations for auto-generated list types. }' + NL +
      OutputListForwardDecls + NL;

  if OutputEnums <> '' then
    OutputInterface := OutputInterface + OutputEnums;

  OutputInterface := OutputInterface + OutputClasses;

  if OutputListDefs <> '' then
    OutputInterface := OutputInterface +
      '  { Auto-generated list type definitions. }' + NL +
      OutputListDefs;
end;

{ routines ------------------------------------------------------------------ }

procedure DownloadSchema;
var
  SchemaStream: TMemoryStream;
begin
  if FileExists(SchemaFile) then
    Writeln('Schema file exists: ', SchemaFile)
  else
  begin
    Writeln('Schema file does not exist, downloading: ', SchemaFile);
    EnableBlockingDownloads := true;
    SchemaStream := Download(SchemaUrl, [soForceMemoryStream]) as TMemoryStream;
    try
      SchemaStream.SaveToFile(SchemaFile);
    finally FreeAndNil(SchemaStream) end;
  end;
end;

{ Build SimpleTypeRawBase and SimpleTypeEnumNames from all xs:simpleType elements.
  Must be called before IfcTypeFromXsd so that property type resolution works. }
procedure BuildSimpleTypeMap(const Doc: TXmlDocument);
var
  I: TXMLElementIterator;
  Element, Restriction: TDomElement;
  NameIfc, BaseType: String;
  EnumIter: TXMLElementIterator;
  HasEnums: Boolean;
begin
  I := Doc.DocumentElement.ChildrenIterator('xs:simpleType');
  try
    while I.GetNext do
    begin
      Element := I.Current;
      NameIfc := Element.AttributeStringDef('name', '');
      if NameIfc = '' then Continue;

      { Skip List-Xxx helper types used for xs:simpleContent wrapping }
      if IsPrefix('List-', NameIfc, false) then Continue;
      { Skip aggregateType helper }
      if NameIfc = 'aggregateType' then Continue;

      Restriction := Element.Child('xs:restriction', false, true);
      if Restriction = nil then Continue;

      BaseType := Restriction.AttributeStringDef('base', '');
      if BaseType = '' then Continue;

      { Check if this is an enum type (has xs:enumeration children) }
      HasEnums := False;
      EnumIter := Restriction.ChildrenIterator('xs:enumeration');
      try
        if EnumIter.GetNext then
          HasEnums := True;
      finally FreeAndNil(EnumIter) end;

      if HasEnums then
        SimpleTypeEnumNames.Add(NameIfc);

      { Store raw base type for later resolution }
      if not SimpleTypeRawBase.ContainsKey(NameIfc) then
        SimpleTypeRawBase.Add(NameIfc, BaseType);
    end;
  finally FreeAndNil(I) end;
end;

{ Parse properties from an xs:extension element and add them to ComplexType.Properties. }
procedure ParseProperties(const ComplexType: TIfcComplexType;
  const ExtensionElement: TDomElement);
var
  Sequence: TDomElement;
  AttrIter, SeqIter, InnerAttrIter: TXMLElementIterator;
  AttrElement, SeqElement, InlineComplexType: TDomElement;
  PropName, PropTypeIfc, PropTypePascal, ItemTypeIfc, ItemTypePascal: String;
  Prop: TIfcProperty;
  Kind: TIfcPropertyKind;
begin
  { Parse xs:attribute children -> scalar/enum properties }
  AttrIter := ExtensionElement.ChildrenIterator('xs:attribute');
  try
    while AttrIter.GetNext do
    begin
      AttrElement := AttrIter.Current;
      PropName := AttrElement.AttributeStringDef('name', '');
      PropTypeIfc := AttrElement.AttributeStringDef('type', '');

      { Skip attributes without name (like ref="ifc:itemType") }
      if PropName = '' then Continue;
      { Skip attributes without explicit type (inline simpleType, e.g. Coordinates) }
      if PropTypeIfc = '' then Continue;

      { Resolve the type }
      PropTypePascal := ResolveSimpleType(PropTypeIfc);
      if PropTypePascal = '' then
      begin
        Writeln('Warning: Cannot resolve attribute type ', PropTypeIfc,
          ' for property ', PropName, ' of ', ComplexType.NameIfc, ', skipping');
        Continue;
      end;

      { Determine the property kind from the resolved Pascal type }
      if PropTypePascal = 'String' then
        Kind := pkString
      else if PropTypePascal = 'Single' then
        Kind := pkFloat
      else if PropTypePascal = 'Integer' then
        Kind := pkInteger
      else if PropTypePascal = 'Boolean' then
        Kind := pkBoolean
      else
        Kind := pkEnum;

      Prop := TIfcProperty.Create;
      Prop.NameIfc := PropName;
      Prop.NamePascal := PascalPropertyName(PropName);
      Prop.Kind := Kind;
      Prop.TypePascal := PropTypePascal;
      ComplexType.Properties.Add(Prop);
    end;
  finally FreeAndNil(AttrIter) end;

  { Parse xs:element children in xs:sequence -> reference/list properties }
  Sequence := ExtensionElement.Child('xs:sequence', false, true);
  if Sequence <> nil then
  begin
    SeqIter := Sequence.ChildrenIterator('xs:element');
    try
      while SeqIter.GetNext do
      begin
        SeqElement := SeqIter.Current;
        PropName := SeqElement.AttributeStringDef('name', '');
        if PropName = '' then Continue;

        PropTypeIfc := SeqElement.AttributeStringDef('type', '');

        if PropTypeIfc <> '' then
        begin
          { Single instance reference property }
          PropTypePascal := TIfcType.IfcNameToPascal(PropTypeIfc);

          Prop := TIfcProperty.Create;
          Prop.NameIfc := PropName;
          Prop.NamePascal := PascalPropertyName(PropName);
          Prop.Kind := pkReference;
          Prop.TypePascal := PropTypePascal;
          ComplexType.Properties.Add(Prop);
        end else
        begin
          { Check for inline complexType -> list property }
          InlineComplexType := SeqElement.Child('xs:complexType', false, true);
          if InlineComplexType <> nil then
          begin
            { Look for ifc:itemType attribute to identify list item type }
            ItemTypeIfc := '';
            InnerAttrIter := InlineComplexType.ChildrenIterator('xs:attribute');
            try
              while InnerAttrIter.GetNext do
              begin
                if InnerAttrIter.Current.AttributeStringDef('ref', '') = 'ifc:itemType' then
                begin
                  ItemTypeIfc := InnerAttrIter.Current.AttributeStringDef('fixed', '');
                  Break;
                end;
              end;
            finally FreeAndNil(InnerAttrIter) end;

            if ItemTypeIfc <> '' then
            begin
              ItemTypePascal := TIfcType.IfcNameToPascal(ItemTypeIfc);
              PropTypePascal := ItemTypePascal + 'List';

              Prop := TIfcProperty.Create;
              Prop.NameIfc := PropName;
              Prop.NamePascal := PascalPropertyName(PropName);
              Prop.Kind := pkList;
              Prop.TypePascal := PropTypePascal;
              Prop.ListItemTypePascal := ItemTypePascal;
              ComplexType.Properties.Add(Prop);
            end;
          end;
        end;
      end;
    finally FreeAndNil(SeqIter) end;
  end;
end;

procedure IfcTypeFromXsd(const Element: TDomElement);
var
  NameIfc, NamePascal: String;
  ComplexContent, ExtensionEl, RestrictionEl, ExtensionOrRestriction: TDomElement;
  ComplexType: TIfcComplexType;
  Restriction: TDomElement;
  EnumIter: TXMLElementIterator;
  EnumType: TIfcEnumType;
begin
  NameIfc := Element.AttributeString('name');
  NamePascal := TIfcType.IfcNameToPascal(NameIfc);

  //Writeln('Processing ', NameIfc, ' -> ', NamePascal);

  // It seems root level for IFC file? or some internal XSD helper type?
  // we use TIfcFile for this.
  if SameText(NameIfc, 'ifcXML') then
    Exit;

  if Element.TagName8 = 'xs:complexType' then
  begin
    { Detect declarations like
        TIfcObjectPlacement = class abstract(TIfcPersistent)
        TIfcCartesianPoint = class(TIfcPoint)
      Do not detect forward declarations like
        TIfcIndexedColourMap = class;
      as castleifc_ifc_standard_types.inc has some forward declarations
      resolved only in castleifc_ifc_standard_types_autogenerated.inc . }
    if IsManuallyDefined(NamePascal) then
      Exit;

    ComplexContent := Element.Child('xs:complexContent', false, true);
    if ComplexContent <> nil then
    begin
      ExtensionEl := ComplexContent.Child('xs:extension', false, true);
      RestrictionEl := ComplexContent.Child('xs:restriction', false, true);

      if ExtensionEl <> nil then
        ExtensionOrRestriction := ExtensionEl
      else
        ExtensionOrRestriction := RestrictionEl;

      if ExtensionOrRestriction <> nil then
      begin
        // create and add TIfcComplexType instance
        ComplexType := TIfcComplexType.Create;
        ComplexType.Abstract := Element.AttributeBooleanDef('abstract', false);
        ComplexType.NameIfc := NameIfc;
        ComplexType.NamePascal := NamePascal;
        ComplexType.BaseIfc := ExtensionOrRestriction.AttributeString('base');
        ComplexType.BasePascal := TIfcType.IfcNameToPascal(ComplexType.BaseIfc);
        ComplexType.IsExtension := (ExtensionEl <> nil);

        { Parse properties only from xs:extension (not xs:restriction).
          xs:restriction only constrains existing parent properties. }
        if ComplexType.IsExtension then
          ParseProperties(ComplexType, ExtensionEl);

        IfcTypes.Add(ComplexType);
      end;
    end;
  end else
  if Element.TagName8 = 'xs:simpleType' then
  begin
    { Generate enum types }
    if IsManuallyDefined('T' + NameIfc) then
      Exit;

    Restriction := Element.Child('xs:restriction', false, true);
    if Restriction = nil then Exit;

    { Check if this is an enum (has xs:enumeration children) }
    EnumIter := Restriction.ChildrenIterator('xs:enumeration');
    try
      if not EnumIter.GetNext then
        Exit; { not an enum, skip }

      EnumType := TIfcEnumType.Create;
      EnumType.NameIfc := NameIfc;
      EnumType.NamePascal := 'T' + NameIfc;
      repeat
        EnumType.Values.Add(EnumIter.Current.AttributeString('value'));
      until not EnumIter.GetNext;
      IfcTypes.Add(EnumType);
    finally FreeAndNil(EnumIter) end;
  end;
end;

{ Just like UrlReadXml, but forces encoding from ASCII to UTF-8.
  Reason: IFC XSD uses ASCII encoding,

    <?xml version='1.0' encoding='ASCII'?>

  which causes

    Encoding 'ASCII' is not supported (in file "IFC4X3_ADD2.xsd")

  error from FPC XMLRead (because TXMLDecodingSource.SetEncoding
  does not support ASCII). }
function UrlReadXml_ForceEncodingUtf8(const Url: String): TXmlDocument;
var
  Stream: TStream;
  Str: String;
  NewStream: TStringStream;
begin
  Stream := Download(Url);
  try
    Str := ReadGrowingStreamToDefaultString(Stream);
    Str := StringReplace(Str, 'encoding=''ASCII''', 'encoding=''UTF-8''', []);
    NewStream := TStringStream.Create(Str);
    try
      ReadXmlFile(Result, NewStream);
    finally FreeAndNil(NewStream) end;
  finally FreeAndNil(Stream) end;
end;

var
  Doc: TXmlDocument;
  I: TXMLElementIterator;
  OutputInclude, OutputInterface, OutputImplementation, OutputAddClasses: String;
begin
  DownloadSchema;

  { All global instances are nil, use this to have less nesting in try..finally. }
  try
    ManuallyDefinedTypes := FileToString(ManuallyDefinedTypesUnit);

    SimpleTypeRawBase := TStringStringDictionary.Create;
    SimpleTypeEnumNames := TStringList.Create;
    SimpleTypeEnumNames.Sorted := True;
    SimpleTypePascalCache := TStringStringDictionary.Create;

    IfcTypes := TIfcTypeList.Create(true);

    Doc := UrlReadXml_ForceEncodingUtf8(SchemaFile);
    try
      { First pass: build simple type map for property type resolution }
      BuildSimpleTypeMap(Doc);

      { Second pass: process all types }
      I := Doc.DocumentElement.ChildrenIterator;
      try
        while I.GetNext do
          IfcTypeFromXsd(I.Current);
      finally FreeAndNil(I) end;
    finally FreeAndNil(Doc) end;

    IfcTypes.ResolveAncestors;
    IfcTypes.Sort(TIfcTypeComparer.Construct(
      {$ifdef FPC}@{$endif} IfcTypes.CompareIfcTypes));
    IfcTypes.MakeOutput(OutputInterface, OutputImplementation, OutputAddClasses);

    OutputInclude :=
      '{%MainUnit castleifc.pas}' + NL +
      '{ Auto-generated IFC classes definitions by generate_ifc. }' + NL +
      '{$ifdef read_interface_types}' + NL +
      '//type' + NL +
      OutputInterface +
      '{$endif read_interface_types}' + NL +
      NL +
      '{$ifdef read_implementation}' + NL +
      OutputImplementation + NL +
      '{$endif read_implementation}' + NL +
      NL +
      '{$ifdef read_add_classes}' + NL +
      OutputAddClasses + NL +
      '{$endif read_add_classes}';
    StringToFile(OutputPath, OutputInclude);
  finally
    FreeAndNil(IfcTypes);
    FreeAndNil(SimpleTypeRawBase);
    FreeAndNil(SimpleTypeEnumNames);
    FreeAndNil(SimpleTypePascalCache);
  end;
end.
