{
  Copyright 2003-2004 Michalis Kamburelis.

  This file is part of "Kambi's 3dmodels Pascal units".

  "Kambi's 3dmodels Pascal units" is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  "Kambi's 3dmodels Pascal units" is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with "Kambi's 3dmodels Pascal units"; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
}

{ This is an example how to use units VRMLNodes and Object3dAsVRML
  to write a simple converter from 3DS, OBJ and GEO to VRML 1.0.
  This program reads a model from filename given as parameter
  ('-' means stdin), and outputs model as VRML 1.0 to stdout.

  Note that it can also "convert" VRML 1.0 to VRML 1.0,
  this will remove all comments from input VRML and it will
  nicely format (pretty-print) output VRML.

  One real use of this program is to use it instead of view3dscene
  with --write-to-vrml parameter. This way you don't need
  e.g. OpenGL libraries (that are required to run view3dscene)
  installed on your system to perform convertion from 3DS to VRML.

  Second real use would be to modify this program to perform some
  processing of Node before it's saved to file.
  This way you write programs that process VRML files in many ways,
  e.g. change the names/order of nodes, convert some nodes
  to others, delete/add some nodes etc.
}

program many2vrml;

uses SysUtils, KambiUtils, KambiClassUtils, VRMLNodes, Object3dAsVRML;

var Node: TVRMLNode;
begin
 ParCountEqual(1);
 Node := LoadAsVRML(ParStr(1), true);
 try
  SaveToVRMLFile(Node, StdOutStream,
    'VRML generated by many2vrml by Kambi from '
    +ParStr(1) +' on ' +DateToStr(Date) +' at ' +TimetoStr(now));
 finally Node.Free end;
end.