{ Unit using all the testcases in units TestXxx.

  Why this way?

  - We cannot use all TestXxx from GameInitialize, because GameInitialize
    is shared with other projects using our CastleTester,
    in particular tools/build-tool/tests/ .

  - We cannot use all TestXxx only from castle_tester_standalone.dpr,
    because this code is only used on desktop platforms.
    We want to run all testcases also e.g. on web through
    https://castle-engine.io//web-demos/tests/
}
unit TestCases;

interface

uses
  { Testing (mainly) things inside Pascal standard library, not CGE }
  TestCompiler,
  TestSysUtils,
  {$ifdef FPC}TestFGL,{$endif}
  TestGenericsCollections,
  {$ifdef FPC}TestOldFPCBugs,{$endif}
  {$ifdef FPC}TestFPImage,{$endif}
  //TestToolFpcVersion,

  { Testing CGE units }
  TestCastleUtils,
  TestCastleRectangles,
  TestCastleFindFiles,
  TestCastleFilesUtils,
  TestCastleUtilsLists,
  TestCastleClassUtils,
  TestCastleVectors,
  TestCastleTriangles,
  TestCastleColors,
  TestCastleQuaternions,
  TestCastleRenderOptions,
  TestCastleKeysMouse,
  TestCastleImages,
  TestCastleInternalDataCompression,
  TestCastleImagesDraw,
  TestCastleBoxes,
  TestCastleFrustum,
  TestCastleInternalGLShadowVolumes,
  TestCastleFonts,
  TestCastleTransform,
  TestCastleParameters,
  TestCastleUIControls,
  TestCastleCameras,
  TestX3DFields,
  TestX3DNodes,
  TestX3DNodesOptimizedProxy,
  TestX3DNodesNurbs,
  TestCastleRendererInternalShader,
  TestCastleScene,
  TestCastleSceneCore,
  TestCastleSceneManager,
  TestCastleVideos,
  TestCastleSpaceFillingCurves,
  TestCastleStringUtils,
  TestCastleScript,
  TestCastleScriptVectors,
  TestCastleCubeMaps,
  TestCastleGLVersion,
  TestCastleCompositeImage,
  TestCastleTriangulate,
  TestCastleGame,
  TestCastleUriUtils,
  TestCastleInternalDataUri,
  TestCastleXmlUtils,
  TestCastleCurves,
  TestCastleTimeUtils,
  TestCastleControls,
  TestCastleSoundEngine,
  TestCastleComponentSerialize,
  TestCastleDesignComponents,
  TestX3DLoadInternalUtils,
  TestCastleLevels,
  TestCastleDownload,
  TestCastleUnicode,
  TestCastleResources,
  TestX3DLoadGltf,
  TestCastleTiledMap,
  TestCastleInternalAutoGenerated,
  TestCastleLocalizationGetText,
  TestCastleViewport,
  TestCastleInternalRttiUtils,
  TestCastleShapes,
  TestCastleInternalDelphiUtils,
  TestCastleFileFilters,
  TestCastleWindow,
  TestCastleOpeningAndRendering3D,
  TestCastleWindowOpen,
  TestCastleInternalEgl,
  TestCastleInternalTools,
  TestX3DLoadInternalCocos2d,
  TestCastleIfc,
  TestCastleZip,
  TestCastleInternalUrlUtils;

implementation

end.