## google_analytics

Enable the https://www.google.com/analytics/[Google Analytics] analytics of your apps. Use the https://castle-engine.io/apidoc/html/CastleAnalytics.TAnalytics.html[TAnalytics] class from the https://castle-engine.io/apidoc/html/CastleAnalytics.html[CastleAnalytics] unit to initialize and send data to the analytics from your Pascal code. Also, all the purchases done using `google_in_app_purchases` service are automatically send to analytics, with correct price and currency.

Requires:

* Using this service requires using also the `google_play_services` service.
* Recent _Google Analytics_ require you to use a special `google-services.json` file in your project.
 ** On https://developers.google.com/analytics/devguides/collection/android/v4/[this page] click _"Get a
Configuration File"_
 ** On a form that appears, add _"Analytics"_ service to your application, selecting proper _Google Analytics_ account parameters.
 ** Download `google-services.json` from the form above.
 ** Place the contents of this `google-services.json` file inside the link:https://castle-engine.io/project_manifest[CastleEngineManifest.xml] as the parameter of the `google_analytics`, like this:
+
[,xml]
----
<service name="google_analytics">
  <parameter key="game_services_json">
{
  "project_info":
  ......
  "configuration_version": "1"
}
  </parameter>
</service>
----

[NOTE]
====
You need to create a new "property" in _Google Analytics_ for tracking your mobile application, and obtain a "tracking ID" (like `UA-xxx`). However, since Google now advices using Firebase for tracking mobile applications, if you click on "Mobile" when creating a new Google Analytics property, it will suggest you to connect your application to Firebase. Instead, _create a "Website" property in "Google Analytics" to get a normal tracking ID, and then change the "view" to see mobile application data_. See:

* https://stackoverflow.com/questions/44142353/creating-google-analytics-property-not-using-firebase
* https://stackoverflow.com/questions/45853012/add-google-analytics-to-android-app-without-firebase
* https://stackoverflow.com/questions/44421865/is-firebase-now-mandatory-for-use-of-google-analytics-mobile-properties
====
