## facebook

Integrates your application with https://developers.facebook.com/docs/android/[Facebook Core SDK].

## Features

This integration allows to use Facebook Analytics. Various events are logged automatically (like starting the application or making a purchase). You can also log custom events (only _"level achieved"_ for now) by `TFacebook.LogAchievedLevel('level_name')` in Pascal (see `CastleFacebook` unit).

## Usage

You need to link the application to a Facebook application on http://developers.facebook.com/ :

* In `CastleEngineManifest.xml`, you need to specify your Facebook Application _id_ and _client token_ like this:
+
[,xml]
----
  <service name="facebook">
    <parameter key="app_id" value="11223344" />
    <parameter key="client_token" value="...." />
  </service>
----
+
Follow the https://developers.facebook.com/docs/android/getting-started[Facebook SDK: Getting Started] for links how to get this information.

* Fill the necessary information in the Facebook application settings. In particular:
+
You need to provide to Facebook a "key hash" derived from your application signing keys. See the https://developers.facebook.com/docs/app-events/getting-started-app-events-android , section _"3. Add Your Development and Release Key Hashes"_.
+
Do also steps mentioned there in _"4. Tell Us about Your Android Project"_.

## Example

See the `examples/mobile/facebook_integration` for a demo.