#!/bin/bash
set -eu

# ------------------------------------------------------------------------
# Rebuild all web demos linked from https://castle-engine.io/web .
# Copies their output to the (local) cge-www repository.
#
# After executing this, to update website:
#
# - update binaries outside of GIT:
#   rsync -av ~/sources/castle-engine/cge-www/htdocs/web-demos/ ssh.castle-engine.io:/home/michalis/cge-www/htdocs/web-demos
#   ssh ssh.castle-engine.io
#     ~/bin/purge_cache.sh
#
# - not necessary anymore (web-demos in cge-www/.gitignore):
#   update things tracked in GIT:
#   commit + push in cge-www
#   ssh ssh.castle-engine.io
#     ~/bin/www_synchronize_noimages.sh
# ------------------------------------------------------------------------

CGE_WWW_DEMOS="${CASTLE_ENGINE_PATH}/../cge-www/htdocs/web-demos"

# define $FIND, we want GNU find
FIND='find'
if which cygpath.exe > /dev/null; then
  # On Cygwin/MSYS2, make sure to use Cygwin/MSYS2's find, not the one from Windows
  FIND='/bin/find'
fi
if [ "`uname -s`" '=' 'Darwin' ]; then
  FIND='gfind'
fi

# Rebuild and copy project for web.
#
# $1 is project's absolute directory.
#
# $2 is subdirectory within cge-www/.../web-demos/ .
do_project_any ()
{
  local PROJECT_FULL_DIR="$1"
  local PROJECT_SUBDIR="$2"
  shift 2

  cd "${PROJECT_FULL_DIR}"
  castle-engine clean
  castle-engine compile --target=web --mode=release

  CGE_WWW_DIST="${CGE_WWW_DEMOS}/${PROJECT_SUBDIR}"
  rm -Rf "${CGE_WWW_DIST}"
  mkdir -p "${CGE_WWW_DIST}"
  cp -R castle-engine-output/web/dist/* "${CGE_WWW_DIST}"
}

# Rebuild and copy project $1, that is inside CGE.
#
# $1 should be a directory in CGE, like examples/web/simplest_viewport
#
# (it can start with "./" to indicate current dir -- doesn't change anything,
# but it's accepted, as "find" will return paths like
# "./examples/web/simplest_viewport").
do_project ()
{
  local PROJECT_SUBDIR="$1"
  shift 1

  cd "${CASTLE_ENGINE_PATH}/${PROJECT_SUBDIR}"
  castle-engine clean
  castle-engine compile --target=web --mode=release

  CGE_WWW_DIST="${CGE_WWW_DEMOS}/${PROJECT_SUBDIR}"
  rm -Rf "${CGE_WWW_DIST}"
  mkdir -p "${CGE_WWW_DIST}"
  cp -R castle-engine-output/web/dist/* "${CGE_WWW_DIST}"
}

# Find and build *all* projects in CGE, with only some exceptions.
# Unused for now: This is cool, but for now it's OK to list ~20 projects.
# do_all_projects ()
# {
#   cd "${CASTLE_ENGINE_PATH}"
#
# 	"${FIND}" . \
# 	  '(' -path ./tools -prune ')' -o \
# 	  '(' -path ./examples/network/tcp_connection -prune ')' -o \
# 	  '(' -path ./tests/delphi_tests -prune ')' -o \
# 	  '(' -path ./examples/delphi -prune ')' -o \
#     '(' -path ./src/deprecated_library -prune ')' -o \
# 	  '(' -path ./examples/deprecated_library -prune ')' -o \
# 	  '(' -type d -iname castle-engine-output -prune ')' -o \
# 	  '(' -type f -iname CastleEngineManifest.xml -print ')' > \
# 	  /tmp/cge-projects.txt
# 	echo 'Found projects: '`wc -l < /tmp/cge-projects.txt`
#
# 	for MANIFEST in `cat /tmp/cge-projects.txt`; do
#     local PROJECT_SUBDIR=`dirname ${MANIFEST}`
# 	  echo 'Compiling project '${PROJECT_SUBDIR}
#     do_project ${PROJECT_SUBDIR}
# 	done
# }

# main code ---------------------------------------------------------------

#do_all_projects

# Examples tested on the web now:

# initial (simplest) web demos
do_project examples/web/simplest
do_project examples/web/simplest_viewport
do_project examples/web/simplest_invaders

# 2d
do_project examples/platformer # TODO: web: no OpenUrl
do_project examples/component_gallery
do_project examples/animations/play_animation
do_project examples/space_shooter
do_project examples/tiled/map_viewer # TODO: web: no open dialog (works, but could be more impressive)
do_project examples/tiled/strategy_game_demo

# 3d
do_project examples/ifc # TODO: web: no open dialog (works, but could be more impressive)
do_project examples/user_interface/zombie_fighter
do_project examples/viewport_and_scenes/cars_demo
do_project examples/viewport_and_scenes/collisions
do_project examples/eye_of_beholder # TODO: web: fog
do_project examples/creature_behaviors # TODO: web: bump mapping, mouse look
do_project examples/third_person_navigation # TODO: web: mouse look

# 3d, problems critical
# do_project examples/fps_game # TODO: web: bump mapping, mouse look, weird blinking
# do_project examples/terrain # TODO: web: terrain shaders, weird crash
# do_project examples/research_special_rendering_methods/test_rendering_opengl_capabilities/ # TODO: web: weird crash

# not in CGE repo, git clone castle-model-viewer-mobile as a sibling to make this work
do_project_any "${CASTLE_ENGINE_PATH}/../castle-model-viewer-mobile" 'castle-model-viewer-mobile' # TODO: web: no open dialog
do_project_any "${CASTLE_ENGINE_PATH}/../castle-dice-throwing" 'castle-dice-throwing'

# TODO: web: screen effects don't show, also demo crashes on effects switch
# do_project examples/screen_effects_demo

# TODO: web: without WebAudio support, these will be silent; also game_3d_sound likely crashes due to PBR
# do_project examples/audio/game_3d_sound
# do_project examples/audio/play_sounds # proably works, but silent without WebAudio


