#!/usr/bin/env bash
set -euo pipefail

# ----------------------------------------------------------------------------
# Run some CGE tests that can be done from a shell, without the need for any FPC.
# ----------------------------------------------------------------------------

cd "$CASTLE_ENGINE_PATH"

# Test we don't have any examples with invalid qualified_name in CastleEngineManifest.xml .
#
# The CGE examples should all have
#   qualified_name="io.castleengine.xxx.yyy.zzz"
# (xxx.yyy.zzz being application name split into words and separated by dots).
# See https://castle-engine.io/coding_conventions#_examples .
do_test_qualified_name ()
{
  if grep --exclude='*~' --exclude='cge_shell_tests' --recursive --fixed-strings 'qualified_name="com.mycompany'; then
    exit 1
  fi
  if grep --exclude='*~' --exclude='cge_shell_tests' --recursive --fixed-strings 'qualified_name="net.sourceforge'; then
    exit 1
  fi
  if grep --exclude='*~' --exclude='cge_shell_tests' --recursive --fixed-strings 'qualified_name="io.sourceforge'; then
    exit 1
  fi
}

# Test that examples have no leftover "public domain" header.
# Examples are under BSD.
# See https://castle-engine.io/coding_conventions#_examples .
do_test_examples_copyright ()
{
  if grep --exclude='*~' --recursive --fixed-strings 'This code is in public domain, unlike most other CGE code' examples/; then
    exit 1
  fi
  if grep --exclude='*~' --recursive --fixed-strings 'This template code is in public domain, unlike most other CGE code' examples/; then
    exit 1
  fi
}

# Test editor template in build-tool/data/custom_editor_template/ is up-to-date.
# This means that tools/build-tool/data/custom_editor_template_rebuild.sh
# should do nothing.
do_test_custom_editor_template_up_to_date ()
{
  rm -Rf tools/build-tool/data/custom_editor_template-temptest/
  cp -R  tools/build-tool/data/custom_editor_template/ \
         tools/build-tool/data/custom_editor_template-temptest/
  cd tools/build-tool/data/
  ./custom_editor_template_rebuild.sh
  diff -ur custom_editor_template/ \
           custom_editor_template-temptest/
  cd ../../../
  rm -Rf tools/build-tool/data/custom_editor_template-temptest/
}

do_test_qualified_name
do_test_examples_copyright
do_test_custom_editor_template_up_to_date
