#!/usr/bin/env bash
set -exuo pipefail

# ----------------------------------------------------------------------------
# Run some CGE tests that can be done from a shell, without the need for any FPC.
# ----------------------------------------------------------------------------

cd "$CASTLE_ENGINE_PATH"

# --------------------------------------------------------------------------
# detect tools with OS-specific names

FIND='find'
if which cygpath.exe > /dev/null; then
  FIND='/bin/find' # On Cygwin, make sure to use Cygwin's find, not the one from Windows
fi

# --------------------------------------------------------------------------
# routines performing specific tests

# Test we don't have any projects with invalid qualified_name
# in CastleEngineManifest.xml .
do_test_qualified_name ()
{
  # For all projects: make sure they don't contain invalid qualified_name
  # (it is OK to not have qualified_name at all, for now, for tools).
  find . -name CastleEngineManifest.xml | while read -r CGE_MANIFEST_FILENAME; do
    echo "Checking no invalid qualified name: ${CGE_MANIFEST_FILENAME}"
    if grep --fixed-strings 'qualified_name="com.mycompany' "${CGE_MANIFEST_FILENAME}"; then
      exit 1
    fi
    if grep --fixed-strings 'qualified_name="net.sourceforge' "${CGE_MANIFEST_FILENAME}"; then
      exit 1
    fi
    if grep --fixed-strings 'qualified_name="io.sourceforge' "${CGE_MANIFEST_FILENAME}"; then
      exit 1
    fi

    set +e # ignore wc exit code (wc may return 1 if no lines)
    LINES=$(grep -c --fixed-strings 'qualified_name="' "${CGE_MANIFEST_FILENAME}")
    set -e

    if [[ "${LINES}" -ne 1 && "${LINES}" -ne 0 ]]; then
      echo "Error: ${CGE_MANIFEST_FILENAME} has > 1 line with qualified_name"
      exit 1
    fi
  done

  # For examples/ projects: make sure they contain valid qualified_name.
  #
  # The CGE examples should all have
  #   qualified_name="io.castleengine.xxx.yyy.zzz"
  # (xxx.yyy.zzz being application name split into words and separated by dots).
  # See https://castle-engine.io/coding_conventions#_examples .
  find examples/ -name CastleEngineManifest.xml | while read -r CGE_MANIFEST_FILENAME; do
    echo "Checking only valid: ${CGE_MANIFEST_FILENAME}"
    if ! grep --fixed-strings 'qualified_name="io.castleengine' "${CGE_MANIFEST_FILENAME}"; then
      echo "Error: ${CGE_MANIFEST_FILENAME} should have qualified_name starting with io.castleengine"
      exit 1
    fi
  done
}

# Test that examples have no leftover "public domain" header.
# Examples are under BSD.
# See https://castle-engine.io/coding_conventions#_examples .
do_test_examples_copyright ()
{
  if grep --exclude='*~' --recursive --fixed-strings 'This code is in public domain, unlike most other CGE code' examples/; then
    exit 1
  fi
  if grep --exclude='*~' --recursive --fixed-strings 'This template code is in public domain, unlike most other CGE code' examples/; then
    exit 1
  fi
}

# Test editor template in build-tool/data/custom_editor_template/ is up-to-date.
# This means that tools/build-tool/data/custom_editor_template_rebuild.sh
# should do nothing.
do_test_custom_editor_template_up_to_date ()
{
  rm -Rf tools/build-tool/data/custom_editor_template-temptest/
  cp -R  tools/build-tool/data/custom_editor_template/ \
         tools/build-tool/data/custom_editor_template-temptest/
  cd tools/build-tool/data/
  ./custom_editor_template_rebuild.sh
  diff -ur custom_editor_template/ \
           custom_editor_template-temptest/
  cd ../../../
  rm -Rf tools/build-tool/data/custom_editor_template-temptest/
}

# Check that Delphi packages do not refer to VCL or FMX when they should not.
do_test_packages_dependencies ()
{
  if grep --ignore-case 'vcl' packages/delphi/castle_engine.dpk; then
    echo 'Error: packages/delphi/castle_engine.dpk should not depend on VCL'
    exit 1
  fi
  if grep --ignore-case 'fmx' packages/delphi/castle_engine.dpk; then
    echo 'Error: packages/delphi/castle_engine.dpk should not depend on FMX'
    exit 1
  fi

  if grep --ignore-case 'vcl' packages/delphi/castle_engine_fmx.dpk; then
    echo 'Error: packages/delphi/castle_engine_fmx.dpk should not depend on VCL'
    exit 1
  fi

  if grep --ignore-case 'fmx' packages/delphi/castle_engine_vcl.dpk; then
    echo 'Error: packages/delphi/castle_engine_vcl.dpk should not depend on FMX'
    exit 1
  fi
}

# Check that Delphi packages do not contain invalid DeployFile config,
# pointing to absolute paths on specific disk (specific to given computer,
# and Delphi version)
# or relative (which are also wrong in this case, as we don't know Delphi BPL
# location relative to the CGE).
# They should instead point using env variables, defined by Delphi,
# like `$(BDSCOMMONDIR)\Bpl\castle_engine_design.bpl` .
# See packages/delphi/README.md .
#
# This intends to catch errors like this in DPROJ files:
#
#   <DeployFile LocalName="C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\castle_engine_design.bpl"  Configuration="Debug" Class="ProjectOutput">
#
# or
#
#   <DeployFile LocalName="..\..\..\..\..\Public\Documents\Embarcadero\Studio\23.0\Bpl\castle_engine_window.bpl" Configuration="Debug" Class="ProjectOutput">
#
# These should use
#
do_test_no_invalid_deploy_files ()
{
  if grep --ignore-case --fixed-strings '<DeployFile LocalName="c:' packages/delphi/*.dproj; then
    echo 'Error: packages/delphi/*.dproj should not contain hardcoded absolute paths in DeployFile'
    exit 1
  fi
  if grep --ignore-case --fixed-strings '<DeployFile LocalName="d:' packages/delphi/*.dproj; then
    echo 'Error: packages/delphi/*.dproj should not contain hardcoded absolute paths in DeployFile'
    exit 1
  fi
  if grep --ignore-case --fixed-strings '<DeployFile LocalName="e:' packages/delphi/*.dproj; then
    echo 'Error: packages/delphi/*.dproj should not contain hardcoded absolute paths in DeployFile'
    exit 1
  fi

  if grep --ignore-case --fixed-strings '<DeployFile LocalName="..' packages/delphi/*.dproj; then
    echo 'Error: packages/delphi/*.dproj should not contain relative paths in DeployFile'
    exit 1
  fi
}

# Examples should not have .gitignore files.
# (because there are lots of examples, better list their binaries in one top-level .gitignore).
do_test_examples_no_gitignore ()
{
  # Do not search cpp_builder below -- this is an exception to our rule,
  # as with C++ Builder we ignore a few special files.

  "${FIND}" examples/ \
    '(' -type d -name 'cpp_builder' -prune ')' -or \
    '(' \
      '(' -iname CastleEngineManifest.xml ')' -and \
      '(' -name .gitignore ')' \
      '(' -print0 ')' \
    ')' | while read -rd $'\0' FILE; do
    echo "Error: ${FILE} should not exist, we have one top-level .gitignore"
    exit 1
  done
}

# Analyze path lengths within CGE repository.
#
# We try to limit ourselves, to not hit too soon:
# 1. Windows long paths limit
# 2. GIT on Windows paths limit
#
# See
# - https://www.supportyourtech.com/articles/how-to-enable-long-paths-in-windows-11-step-by-step-guide/
# - https://technofossy.com/how-to-fix-filename-too-long-errors-in-git-on-windows/
#
# Note: the problem is in general not possible to avoid, since users
# can install CGE in already-long paths.
# Also, our build tool can create super long paths within,
# like Android can create:
# xxx/castle-engine-output/android/project/app/build/intermediates/desugar_graph/debug/out/currentProject/jar_6f952a041434a249b77470de1f1a7ef58277461d633a2e42644e1add6726a3f6_bucket_0/graph.bin
# (that's almost 200 chars, and we're not responsible for most of them).
#
# So we just try to limit ourselves to something reasonable
# to minimize changes of possible issues.
do_longest_path ()
{
  # Look only at versioned files.
  # To list all, try
  #   "${FIND}" . -type f
  # but note it depends on previous state, for what platforms and what did we compile.

  # We need to change core.quotePath, otherwise some of our test files
  # with Chinese etc. characters inside would seem to be longest.
  #git config core.quotePath
  git config core.quotePath false

  LONGEST_PATH_LENGTH=$(
    git ls-tree --full-tree -r --name-only HEAD  | \
    awk '{ print length, $0 }' | \
    sort -n | \
    tail -n 1 | \
    cut -d ' ' -f 1)
  MAX_LONGEST_PATH_LENGTH=130

  if [[ "${LONGEST_PATH_LENGTH}" -gt "${MAX_LONGEST_PATH_LENGTH}" ]]; then
    echo "Error: longest path in CGE repository is $LONGEST_PATH_LENGTH, should be <= $MAX_LONGEST_PATH_LENGTH"
    echo "Here are 10 files with longest paths"
    git ls-tree --full-tree -r --name-only HEAD  | \
      awk '{ print length, $0 }' | \
      sort -n | \
      tail -n 10
    exit 1
  fi

  git config --unset core.quotePath
}

# main -----------------------------------------------------------------------

do_test_qualified_name
do_test_examples_copyright
do_test_custom_editor_template_up_to_date
do_test_packages_dependencies
do_test_no_invalid_deploy_files
do_test_examples_no_gitignore
do_longest_path
