#!/usr/bin/env bash
set -euo pipefail

# Execute in top-level CGE dir.
# Tries to compile lazbuild $@
# (i.e. all script arguments are just passed to lazbuild).
#
# In case it fails (as lazbuild fails with access violation sometimes:
#  An unhandled exception occurred at $0000000000575F5F:
#   EAccessViolation: Access violation
#     $0000000000575F5F line 590 of exttools.pas
#     $000000000057A027 line 1525 of exttools.pas
#     $000000000057B231 line 1814 of exttools.pas
# )
# ... the script will clean CGE dir and just retry.

if ! lazbuild "$@"; then
  echo '1st execution of lazbuild failed, trying again'
  make clean
  lazbuild "$@"
fi
