# Configure project for CocoaPods.
# The Castle Game Engine build tool will enable some pods and run "pod install"
# (thus making this file actually relevant) *only if some service will actually
# require using CocoaPods*.
# This way developer doesn't need to install CocoaPods, if not using
# any service that requires them.

platform :ios, '8.0'

target '${CAPTION}' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # The line below will be replaced by Podfile contents from all used services.
  ### SERVICES-PODFILES ###
end
