#include <iostream>
#include <tchar.h>

#pragma link "CastleWindow"

#include "CastleWindow.hpp"
#include "CastleApplicationProperties.hpp"
#include "CastleLog.hpp"

#include "GameInitialize.h"

/* Configure ApplicationProperties, start logging.
   For Pascal projects, these calls are autogenerated in castleautogenerated.pas .
   None of these are critical for the project to really work,
   but we show how to express in C++ 100% of the API available from Pascal. */
void EarlyInitialization()
{
	ApplicationProperties()->ApplicationName = "CastleCppWindow";
	ApplicationProperties()->Caption = "C++ Builder Demo Using TCastleWindow";
	ApplicationProperties()->Version = "0.1";
	if (!IsLibrary) {
		Application()->ParseStandardParameters();
	}
	InitializeLog();
}

int _tmain(int argc, _TCHAR* argv[])
{
	EarlyInitialization();

	/* Sets Application()->MainWindow, Application()->OnApplicationInitialize */
	GameInitialize();

	/* Open Application()->MainWindow and run application loop */
	Application()->MainWindow->OpenAndRun();
}

// TODO: How to request Windows GUI application?
// In Pascal: {$apptype GUI}

// TODO: How to request from C++ to use dedicated GPU on laptops?
// We do this in Pascal, see https://castle-engine.io/dedicated_gpu

