## google_analytics

Integration with the https://analytics.google.com/[Google Analytics].

From you game Pascal code, use https://castle-engine.io/apidoc/html/CastleAnalytics.TAnalytics.html[TAnalytics class in the CastleAnalytics unit]. Initialize them with https://castle-engine.io/apidoc/html/CastleAnalytics.TAnalytics.html#InitializeGoogleAnalytics[InitializeGoogleAnalytics method] and send events to the analytics service using various methods like https://castle-engine.io/apidoc/html/CastleAnalytics.TAnalytics.html#Event[Event]. *Also, all the purchases done using `in_app_purchases` service are automatically send to analytics, with correct price and currency.*

Note that you _can_ have both _Game Analytics_ and _Google Analytics_ initialized at the same time. We will send all events to both of them.

This service uses CocoaPods, so make sure you have CocoaPods installed. See https://castle-engine.io/ios_services .

[NOTE]
====
You need to create a new "property" in _Google Analytics_ for tracking your mobile application, and obtain a "tracking ID" (like `UA-xxx`). However, since Google now advices using Firebase for tracking mobile applications, if you click on "Mobile" when creating a new Google Analytics property, it will suggest you to connect your application to Firebase. Instead, _create a "Website" property in "Google Analytics" to get a normal tracking ID, and then change the "view" to see mobile application data_. See:

* https://stackoverflow.com/questions/44142353/creating-google-analytics-property-not-using-firebase
* https://stackoverflow.com/questions/45853012/add-google-analytics-to-android-app-without-firebase
* https://stackoverflow.com/questions/44421865/is-firebase-now-mandatory-for-use-of-google-analytics-mobile-properties
====
