{
  Copyright 2023-2025 Michalis Kamburelis.

  This file is part of "Castle Game Engine".

  "Castle Game Engine" is free software; see the file COPYING.txt,
  included in this distribution, for details about the copyright.

  "Castle Game Engine" is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

  ----------------------------------------------------------------------------
}

{ Unsupported X3D nodes.
  These nodes are defined to follow the latest X3D specification,
  and we can perfectly read and write them in X3D, but nothing more.
  These nodes do not cause any functionality (rendering, interaction, etc.)
  in Castle Game Engine @italic(for now).
  So there's no point using them in Pascal application (unless you'd want
  to generate X3D files to be consumed by other applications, but this is
  not a common CGE use-case).

  We deliberately define them in this internal unit, not in X3DNodes unit,
  to limit their usage by mistake.
  E.g. we don't want developers to accidentally use (unsupported)
  TTextureProjectorNode in their code, inatead of (supported)
  TProjectedTextureCoordinateNode. }
unit CastleInternalNodesUnsupported;

interface

uses X3DNodes, X3DFields, CastleVectors, CastleStringUtils, CastleColors,
  CastleTimeUtils, CastleUtils, CastleBoxes;

type
  {$define read_interface_forwards}

  // registration crafted by hand
  {$I x3dnodes_standard_geospatial.inc}
  {$I x3dnodes_standard_dis.inc}
  {$I x3dnodes_standard_layering.inc}
  {$I x3dnodes_standard_layout.inc}
  {$I x3dnodes_standard_rigidbodyphysics.inc}
  {$I x3dnodes_standard_picking.inc}
  {$I x3dnodes_standard_followers.inc}
  {$I x3dnodes_standard_particlesystems.inc}
  {$I x3dnodes_standard_textureprojector.inc}

  // registration generated by x3d-nodes-to-pascal
  {$I auto_generated_node_helpers/x3dnodes_section_soundx3d4.inc}
  {$I auto_generated_node_helpers/x3dnodes_section_volumerendering.inc}
  {$undef read_interface_forwards}

  {$define read_interface}

  // registration crafted by hand
  {$I x3dnodes_standard_geospatial.inc}
  {$I x3dnodes_standard_dis.inc}
  {$I x3dnodes_standard_layering.inc}
  {$I x3dnodes_standard_layout.inc}
  {$I x3dnodes_standard_rigidbodyphysics.inc}
  {$I x3dnodes_standard_picking.inc}
  {$I x3dnodes_standard_followers.inc}
  {$I x3dnodes_standard_particlesystems.inc}
  {$I x3dnodes_standard_textureprojector.inc}

  // enums for registration generated by x3d-nodes-to-pascal
  {$I x3dnodes_section_soundx3d4_enums.inc}
  {$I x3dnodes_section_volumerendering_enums.inc}

  // registration generated by x3d-nodes-to-pascal
  {$I auto_generated_node_helpers/x3dnodes_section_soundx3d4.inc}
  {$I auto_generated_node_helpers/x3dnodes_section_volumerendering.inc}
  {$undef read_interface}

procedure RegisterUnsupportedNodes;

implementation

uses SysUtils;

{$define read_implementation}

// registration crafted by hand
{$I x3dnodes_standard_geospatial.inc}
{$I x3dnodes_standard_dis.inc}
{$I x3dnodes_standard_layering.inc}
{$I x3dnodes_standard_layout.inc}
{$I x3dnodes_standard_rigidbodyphysics.inc}
{$I x3dnodes_standard_picking.inc}
{$I x3dnodes_standard_followers.inc}
{$I x3dnodes_standard_particlesystems.inc}
{$I x3dnodes_standard_textureprojector.inc}

// enums for registration generated by x3d-nodes-to-pascal
{$I x3dnodes_section_soundx3d4_enums.inc}
{$I x3dnodes_section_volumerendering_enums.inc}

// registration generated by x3d-nodes-to-pascal
{$I auto_generated_node_helpers/x3dnodes_section_soundx3d4.inc}
{$I auto_generated_node_helpers/x3dnodes_section_volumerendering.inc}

procedure RegisterUnsupportedNodes;
begin
  RegisterDISNodes;
  RegisterGeospatialNodes;
  RegisterLayeringNodes;
  RegisterLayoutNodes;
  RegisterRigidBodyPhysicsNodes;
  RegisterPickingNodes;
  RegisterFollowersNodes;
  RegisterParticleSystemsNodes;
  RegisterTextureProjectorNodes;
  RegisterSoundX3D4Nodes;
  RegisterVolumeRenderingNodes;
end;

end.
