[[actions]]
name = "play"
path = "platformer.exe"

[[actions]]
name = "manual"
path = "https://github.com/castle-engine/castle-engine/blob/master/examples/2d_games/platformer/README.md"

[[actions]]
name = "forums"
path = "https://castle-engine.io/talk.php"
