## giftiz

Enable the http://www.giftiz.com/[Giftiz] integration. Your app notifies Giftiz when the user finished a mission inside your game, and Giftiz gives users (real!) gifts. See http://www.giftiz.com/ website for more information, and contact them to get the necessary SDK and partner id.

Use https://castle-engine.io/apidoc/html/CastleGiftiz.TGiftiz.html[TGiftiz] class from the https://castle-engine.io/apidoc/html/CastleGiftiz.html[CastleGiftiz] unit to control the integration from your Pascal code. Send the "mission complete" message to Giftiz by calling `TGiftiz.MissionComplete;`. Display Giftiz button on top of your game UI using the `TGiftizButton` UI service.

Requires:

* The core of this service is a closed-source library distributed by Giftiz in their SDK.
 ** Unpack the Giftiz SDK to a temporary directory.
 ** Copy the `GiftizSDKLibrary/libs` subdirectory to the `castle_game_engine/tools/build-tool/data/android/integrated-services/giftiz/app/libs`.
 ** Copy the `GiftizSDKLibrary/res` subdirectory to the `castle_game_engine/tools/build-tool/data/android/integrated-services/giftiz/app/src/main/res`. Double-check the path: the `res` goes inside the `app/src/main/`, while the `libs` are in higher-level `app` folder.
 ** Copy the button UI images: from `GiftizSDK_1.5.0/Customize/Border_white` copy the png files to your game's `data/giftiz/` subdirectory. There's an alternative set of images in `Border_no`, and some customization of these images is allowed (see Giftiz SDK for details). Our Pascal integration will automatically load and use these images to display Giftiz button.
* You need to specify Giftiz _partner id_ for integration. Initially this is `TEST_PARTNER_KEY`, and if you're accepted -- Giftiz will send you your real partner id. You declare it in your link:pass:[CastleEngineManifest.xml examples][CastleEngineManifest.xml] file like this:
+
[,xml]
----
<android project_type="integrated">
  <services>
    <service name="giftiz">
      <parameter key="partner_key" value="TEST_PARTNER_KEY" />
    </service>
  </services>
</android>
----
