{ -*- buffer-read-only: t -*- }

{ A string-to-pascal converted XPM file with Castle Game Engine icon }
unit ToolEmbeddedXpmIcon;

interface
uses
  CastleUtils;

const
  XpmIconString =
    '/* XPM */' + NL +
    'static char *castle_game_engine_icon[] = {' + NL +
    '/* columns rows colors chars-per-pixel */' + NL +
    '"256 256 90 1 ",' + NL +
    '"{ c #A2BCB5",' + NL +
    '". c #AB3A58",' + NL +
    '"X c #B94758",' + NL +
    '"o c #AD425E",' + NL +
    '"O c #B85468",' + NL +
    '"+ c #B77179",' + NL +
    '"@ c #B58F91",' + NL +
    '"# c #C34056",' + NL +
    '"$ c #D94657",' + NL +
    '"% c #D75559",' + NL +
    '"& c #E54858",' + NL +
    '"* c #EA5657",' + NL +
    '"= c #F15E56",' + NL +
    '"- c #F26657",' + NL +
    '"; c #F37E58",' + NL +
    '": c #E97458",' + NL +
    '"> c #D25965",' + NL +
    '", c #CC6972",' + NL +
    '"< c #E16765",' + NL +
    '"1 c #B8989C",' + NL +
    '"2 c #B6E1D8",' + NL +
    '"3 c #F58A59",' + NL +
    '"4 c #EE9159",' + NL +
    '"5 c #F9A65A",' + NL +
    '"6 c #ED9B7C",' + NL +
    '"7 c #EF8E6F",' + NL +
    '"8 c #F7B171",' + NL +
    '"9 c #B57A85",' + NL +
    '"0 c #B98E94",' + NL +
    '"q c #D87A85",' + NL +
    '"w c #7BA99F",' + NL +
    '"e c #8DBFB3",' + NL +
    '"r c #7DABA1",' + NL +
    '"t c #8ABBB0",' + NL +
    '"y c #8FC1B6",' + NL +
    '"u c #D5FBF3",' + NL +
    '"i c #A3D4C9",' + NL +
    '"p c #AF8D92",' + NL +
    '"a c #85B5AA",' + NL +
    '"s c #8FBBB1",' + NL +
    '"d c #A7B0AC",' + NL +
    '"f c #A5BAB4",' + NL +
    '"g c #CA9096",' + NL +
    '"h c #F1B68C",' + NL +
    '"j c #F0B1AE",' + NL +
    '"k c #DA9FA3",' + NL +
    '"l c #97C6BC",' + NL +
    '"z c #9FCFC6",' + NL +
    '"x c #D9FEF6",' + NL +
    '"c c #B2CFC8",' + NL +
    '"v c #F6C795",' + NL +
    '"b c #E3CDBA",' + NL +
    '"n c #ECCFB1",' + NL +
    '"m c #E4B7C1",' + NL +
    '"M c #9ACBC1",' + NL +
    '"N c #A3D8CD",' + NL +
    '"B c #A3D5CB",' + NL +
    '"V c #AEDDD3",' + NL +
    '"C c #ADE7DB",' + NL +
    '"Z c #B5E9DE",' + NL +
    '"A c #BDEFE4",' + NL +
    '"S c #D9FEF6",' + NL +
    '"D c #D9D8D0",' + NL +
    '"F c #DBF4E6",' + NL +
    '"G c #FEE8D5",' + NL +
    '"H c #CBF6EB",' + NL +
    '"J c #D9FEF6",' + NL +
    '"K c #DEFEF7",' + NL +
    '"L c #D1F7EF",' + NL +
    '"P c #EAFDF9",' + NL +
    '"I c #FFFFFF",' + NL +
    '"U c #FBEFE9",' + NL +
    '"Y c #F7D5D5",' + NL +
    '"T c #D9FEF6",' + NL +
    '"R c #D7FCF4",' + NL +
    '"E c #A6C5BE",' + NL +
    '"W c #B6E5D8",' + NL +
    '"Q c #CBF4EB",' + NL +
    '"! c #95C9BC",' + NL +
    '"~ c #D5FCF3",' + NL +
    '"^ c #D9FDF6",' + NL +
    '"/ c #D9FEF6",' + NL +
    '"( c #ABD4CA",' + NL +
    '") c #C7F1E7",' + NL +
    '"_ c #CDF4EB",' + NL +
    '"` c #D0F3EB",' + NL +
    '"  c None",' + NL +
    '"] c #B8E3D9",' + NL +
    '"[ c #C5ECE3",' + NL +
    '"{ c #B9ACA9",' + NL +
    '/* pixels */' + NL +
    '"                                                                                                                  ]]Q//uuRM2xSLJJxNSiiu{//E``]                                                                                                                  ",' + NL +
    '"                                                                                                           ]EuRxJJKKJJJJKJPPJJPPKPJJKKPIJJPPPPKHM!!)]                                                                                                           ",' + NL +
    '"                                                                                                      Q/iHJJJJPKJJJJJJJJJJJJJJJJKJJJJJPPJJJJKJJJJJIPJJcRE]]                                                                                                     ",' + NL +
    '"                                                                                                 ][RLKKJPPJJJKKKJJJJJJJJJJJJJJJJKJJJJJJLJJJJKKJJJKKPJJLJIPPLR/]                                                                                                 ",' + NL +
    '"                                                                                             ]ERPPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLJJLR/                                                                                              ",' + NL +
    '"                                                                                          `RLKPJKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLJLPJJKN/]                                                                                          ",' + NL +
    '"                                                                                       ]RLJJJJJJJJJJJJKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPKLu]                                                                                       ",' + NL +
    '"                                                                                    `RKIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKJJPL!]                                                                                    ",' + NL +
    '"                                                                                  {PJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL/                                                                                  ",' + NL +
    '"                                                                               [NPJPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKKR/                                                                               ",' + NL +
    '"                                                                            ]RLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPSE                                                                             ",' + NL +
    '"                                                                           RLLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKPPu                                                                           ",' + NL +
    '"                                                                        `MSKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJu]                                                                        ",' + NL +
    '"                                                                      ]RPPKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJR                                                                       ",' + NL +
    '"                                                                    `xJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKu]                                                                    ",' + NL +
    '"                                                                  ]MPIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKKJu                                                                   ",' + NL +
    '"                                                                 RFLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ/                                                                 ",' + NL +
    '"                                                               ELJLPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKD[                                                               ",' + NL +
    '"                                                             [LPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPR]                                                             ",' + NL +
    '"                                                            RKKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKK{                                                            ",' + NL +
    '"                                                          QLKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL]                                                          ",' + NL +
    '"                                                        ]iJJKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKu                                                         ",' + NL +
    '"                                                       /PJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKS]                                                       ",' + NL +
    '"                                                      RKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKKKR                                                      ",' + NL +
    '"                                                    ]FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJM                                                     ",' + NL +
    '"                                                   uPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLL)                                                   ",' + NL +
    '"                                                  RKKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ!                                                  ",' + NL +
    '"                                                ]LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJS                                                 ",' + NL +
    '"                                               /KKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJS]                                               ",' + NL +
    '"                                              uJKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIE                                              ",' + NL +
    '"                                             MJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJHD88vFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPJ!                                             ",' + NL +
    '"                                            xSJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJh375558nFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPKPR                                            ",' + NL +
    '"                                          `LKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJF6;;7555555vnLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJS                                           ",' + NL +
    '"                                         [PKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb3;;;3555555555vDHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLL                                          ",' + NL +
    '"                                        [KJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFh;;;;;3555555555558vDPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPLx]                                        ",' + NL +
    '"                                       )JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJD7;;;;;;355555555555558FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLF]                                       ",' + NL +
    '"                                     ]EIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;355555555555555FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJP]                                      ",' + NL +
    '"                                     {PPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPF]                                     ",' + NL +
    '"                                    /JKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJP]                                    ",' + NL +
    '"                                   QJJJKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;3355555555555555GJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPPJ]                                   ",' + NL +
    '"                                  /KJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLJHJLJLJLHHJLJJLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJD                                   ",' + NL +
    '"                                 `JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLJJPPPPIIIIIIIIIIIPPPPJJJJLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJS                                  ",' + NL +
    '"                                ]LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLJPPIIIIIIIIIIIIIIIIIIIIIIIIPPPJLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJN                                 ",' + NL +
    '"                               ]LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb3;;;;;;;;355555555555555FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLi                                ",' + NL +
    '"                               SKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLPPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPPLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJu                               ",' + NL +
    '"                              iJJKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555GJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJP/                              ",' + NL +
    '"                             RJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FJJJJJJJJJJJJJJPLphnFJJJJJJLJJJJJJJJLJPPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKJQ                             ",' + NL +
    '"                            EPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FJJJJJJJJJJJJJJdOo4558vFJJJHHJJJJJJJPPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL]                            ",' + NL +
    '"                           [HJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJD3;;;;;;;;355555555555555FJJJJJJJJJJJJc+...4555555vCLLJJJJJPPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKS                            ",' + NL +
    '"                           PJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;;355555555555555FJJJJJJJJJJDp.....4555555558vFJJLPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKJT                           ",' + NL +
    '"                          xIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJHFmDLJJLJJJJJKb;;;;;;;;;355555555555555FHHJJJJJJLgo......:555555555588PIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJI!                          ",' + NL +
    '"                         uKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJD7O.o9kDJJJJJLb;;;;;;;;33555555555555555vnJFJJJgo........4555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJLJJJJJJJJJJJJJJJJJJJJJJJJJJKKPI[                         ",' + NL +
    '"                        [PJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLj3;#o....o9dDJJb;;;;;;;;;3555555555555555555vnHFo.........4555555555555GIIIIIIIIIIIIIImO8vUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJF                         ",' + NL +
    '"                        LKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJD6;;;X.....o...9D7;;;;;3;;;3555555555555555555555h>o........4555555555555GIIIIIIIIIIIImO..5558GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLi                        ",' + NL +
    '"                       iKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJHb3;3;;#o.......X:;;;;;;;;;;;45555555555555555555555554>o.....:555555555555GIIIIIIIIIPmO....555558nUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJP{                       ",' + NL +
    '"                      EJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJh;3;;;3X.......%:;;;;;;;;;;;;55555555555555555555555555554X...4555555555555GIIIIIIIImO......55555555vGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJPI]                      ",' + NL +
    '"                     ]HJJJJJJJJJJJJJJJJJJJJJJJJJJJJJHD7;;;;;;;#o...oX:;;;;;;;;;;;;;;35555555555555555555555555555554%4555555555555GIIIIIImO........55555555558GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJT                      ",' + NL +
    '"                     xJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;;X...o%;3;;;;;;;;;;;;;;3555555555555555555555555555555555555555555555GIIIIUO..........55555555555vIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ{                     ",' + NL +
    '"                    EKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJb;;;;;;;3#o.%:;;;;;;;;;;;;;;;;;3555555555555555555555555555555555555555555555GIIIPY...........55555555555vIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPLJJJJJJJJJJJJJJJJJJJJJJJJJJF                     ",' + NL +
    '"                   ]IPKJJJJJJJJJJJJJJJJJJJJLJJJJJJJJLn;;;;;;;3XX:;;;;;;;;;;;;;;;;;;;3555555555555555555555555555555555555555555555GIIIIU...........45555555555hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJKLM                    ",' + NL +
    '"                   iJJJJJJJJJJJJJJJJJJJJPJnqgDLJJHLJJb3;;;;;;;:;;;;;;;;;;;;;;;;;;;;;3555555555555555555555555555555555555555555555UIIIIY...........45555555555hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPHJJJJJJJJJJJJJJJJJJJJJJJJJJ/                   ",' + NL +
    '"                  )IJJJJJJJJJJJJJJJJJJJJFk;.ooo9kDJJLb;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;35555555555555555555555555555555555555555555558nUIIG...........555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKJJJJJJJJJJJJJJJJJJJJJJJJJJK                   ",' + NL +
    '"                  DJJJJJJJJJJJJJJJJJJKJD7;;o......OpDj;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;35555555555555555555555555555555555555555555555558nY...........555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPKJJJJJJJJJJJJJJJJJJJJJJJJJKR                  ",' + NL +
    '"                 {LJJJJJJJJJJJJJJJJJJLj3;;;o.......opb;;;;;;;;;;;;;;;;;;;;;3;;;;;;;335555555555555555555555555555555555555555555555555554,X........555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKJJJJJJJJJJJJJJJJJJJJJJJJJH]                 ",' + NL +
    '"                ]PPJJJJJJJJJJJJJJJJJDh;;;;;.........gb:3;;;;;;;;;;;;;;;;;;;;;;;;;;;;35555555555555555555555555555555555555555555555555555554:X.o...555555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJN                 ",' + NL +
    '"                iIJJJJJJJJJJJJJJJJJb;;;;;;;#........gb;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;35555555555555555555555555555555555555555555555555555555554,X..555555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJP[                ",' + NL +
    '"               `JJJJJJJJJJJJJJJJJJL6;;;;;;;X........pb;;;;;;;;;;;;;;3;;;;;;;;;;;;;;;35555555555555555555555555555555555555555555555555555555555554<555555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJD                ",' + NL +
    '"               xJJJJJJJJJJJJJJJJJJJ6;;;;;;;X........g7;;;;;;;;;;;;;;;;;;;;;;3;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJ/               ",' + NL +
    '"              `JJJJJJJJJJJJJJJJJJJJ7;;;;;;;X.....oo%;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJ               ",' + NL +
    '"              cJJJJJJJJJJJJJJJJJJJJh;;;;;;;X.....#:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJP{              ",' + NL +
    '"             [JJJJJJJJJJJJJJJJJJJJJ6;;;;;;;X....%3;;;;;;;;3;;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJPH              ",' + NL +
    '"             SJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;X..X:;3;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJKK{             ",' + NL +
    '"            ]PPJJJJJJJJJJJJJJJJJJJJ6;;;;;;;X.<;;;;;;;;;;;;;3;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJKKK             ",' + NL +
    '"            NJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;%;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJKKK/            ",' + NL +
    '"           ]JJJJJJJJJJJJJJJJJJJJJJLh;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;3;355555555555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJKF            ",' + NL +
    '"           iJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJPIE           ",' + NL +
    '"          ]KKJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;355555555555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJx           ",' + NL +
    '"          uJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-==-335555555555555555555555555555555555555555555555555555555555555555555555nIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJ]          ",' + NL +
    '"          IKJJJJJJJJJJJJJJJJJJJJJJL6;;;;3;;;;;3;;;;;;;;;;;;;;;;;;;;;;;;3;;;;;;;3;;======--;35555555555555555555555555555555555555555555555555555555555555555555GIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKJJJJJJJJJJJJJJJJJJJJJJJKM          ",' + NL +
    '"         {PPJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:============--34555555555555555555555555555555555555555555555555555555555555555nIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJPP]         ",' + NL +
    '"         NJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;3;;;;;;;;;;;;;;;;3-==================-3555555555555555555555555555555555555555555555555555555555555nIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILJJJJJJJJJJJJJJJJJJJJJJJJ{         ",' + NL +
    '"        ]JJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;3;;;;;;;;;;;;;;;;;;;;;;;;3-=======================-;355555555555555555555555555555555555555555555555555555555nIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJL         ",' + NL +
    '"        RJJJJJJJJJJJJJJJJJJJJJJJJJJ7;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;=============================;355555555555555555555555555555555555555555555555555555vIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJHQ        ",' + NL +
    '"       ]FJJJJJJJJJJJJJJJJJJJJJJJJJJh;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;3;==================================-;35555555555555555555555555555555555555555555555555vIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJR        ",' + NL +
    '"       /JJJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-=======================================-35555555555555555555555555555555555555555555555vIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJ        ",' + NL +
    '"       TJJJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;3:=============================================;3555555555555555555555555555555555555555555vIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJE       ",' + NL +
    '"       LJJJJJJJJJJJJJJJJJJJJJJJJJJL6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;==================================================-;5555555555555555555555555555555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILJJJJJJJJJJJJJJJJJJJJJJJJx       ",' + NL +
    '"      )JJJJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-===================$*&*===============================-;355555555555555555555555555555555555hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJP]      ",' + NL +
    '"      TIJJJJJJJJJJJJJJJJJJJJJJJJJJJh;;;;;;;;;;;;;;;;;;;;;;;;;;;;:===================%##*&&&&*=================================;355555555555555555555555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJPE      ",' + NL +
    '"      KPJJJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;;;;;;;;===================*####$&&&&&&&&*================================;355555555555555555555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJPx      ",' + NL +
    '"     QKKJJJJJJJJJJJJJJJJJJJJJJJJJJLh;;;;;;;;;;;;;;;;;;;;;;;3;-==================*$#####&&&&&&&&&&&&*================================-345555555555555555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJPJ      ",' + NL +
    '"     RJJJJJJJJJJJJJJJJJJJJJJJJJJKLP6;;;;;;;;;;;;;;;;;;;;;;;-===================$#X#####&&&&&&&&&&&&&&&**===============================-:45555555555555555555558IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJKKQ     ",' + NL +
    '"     LKKJJJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;3;;;;;;;;;;;;;3:===================%#########&&&&&&&&&&&&&&&&&&**================================-;4555555555555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKJJJJJJJJJJJJJJJJJJJJJJJKKR     ",' + NL +
    '"    ]KJKJJJJJJJJJJJJJJJJJJJJJJJJJJJ6;;;;;;;;;;;;;;;;;;;;-==================%###########$&&&&&&&&&&&&&&&&&&&&&*=================================:;555555555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJKL     ",' + NL +
    '"    (JJJJJJJJJJJJJJJJJJJJJJJJJJJJJL6;;;;;;;;;;;;;;;;;3-==================*$############$&&&&&&&&&&&&&&&&&&&&&&&&**================================-;355555555555IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJK]    ",' + NL +
    '"    xJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ7;;;;;;;;;;;;;;;;:==================*###############$&&&&&&&&&&&&&&&&&&&&&&&&&&&*=================================--355555555UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJK(    ",' + NL +
    '"    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJh3;;;;;;;;;;;3:;-==================%################$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&================================-;35855UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJM    ",' + NL +
    '"   QJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFh;;;;;;;;;;;;;-==================$##################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&==================================-77UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJL    ",' + NL +
    '"   {JJJJJJJJJJJJJJJJJJJJJJJJJJJJPFFh;;;;;;;;;;;-===============-==*####################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*============================-=*hYIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJ]   ",' + NL +
    '"   xJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPFk;;;;;;;;;;--===============-*######################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*=========================<jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILJJJJJJJJJJJJJJJJJJJJJJJJJJ/   ",' + NL +
    '"   PKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPh;;;;;;;;-=================*########################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&**================*=*hYIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJR   ",' + NL +
    '"  ]JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJF7;;;;;;-=================*$#########################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*==============-jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJP   ",' + NL +
    '"  EPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJg;;;;;==================%###########################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*============jYIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJKKP]  ",' + NL +
    '"  iIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJh;;--=================&#############################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*=========-jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJKKK[  ",' + NL +
    '"  NJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKFh;:=================*###############################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*=======kYIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJ/  ",' + NL +
    '"  SJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLPk-==*==============$################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&====;jIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJR  ",' + NL +
    '" ]JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLDj7===*=========*#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&**=kYIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJKS  ",' + NL +
    '" [JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPJJFDj7=========&#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&=jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJKK  ",' + NL +
    '" !IIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJDjg--===*#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILJJJJJJJJJJJJJJJJJJJJJJJJJJKJ] ",' + NL +
    '" 2KKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPFLDjg->#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&kIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJQ ",' + NL +
    '" iKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLk#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJE ",' + NL +
    '" FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLm#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&-IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPHJJJJJJJJJJJJJJJJJJJJJJJJJJJJR ",' + NL +
    '" PJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJko################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJR ",' + NL +
    '" KJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJm#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJS ",' + NL +
    '"`PKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJd#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKK ",' + NL +
    '"EPKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJk#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKK ",' + NL +
    '"EJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJk#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ]",' + NL +
    '"!JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJk#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJK]",' + NL +
    '"RPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLk##################################&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJK`",' + NL +
    '"RKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKK/",' + NL +
    '"MPFKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ/",' + NL +
    '"iFKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJK(",' + NL +
    '"xJFKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJK!",' + NL +
    '"SJJKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJR",' + NL +
    '"FPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILPLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJu",' + NL +
    '"FPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPKLPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLR",' + NL +
    '"LLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&UIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLR",' + NL +
    '"LLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJg#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&YIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLR",' + NL +
    '"LJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLq#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&YIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJR",' + NL +
    '"LJJJJJJJJJJJJJJJJJJJJKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ9#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&YIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJR",' + NL +
    '"FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJq#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&YUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKJR",' + NL +
    '"SJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLq#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&YIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKKJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPP!",' + NL +
    '"SKKKJJJJJJJJJJJJJJJJJJJJJJJJJKJJJJJJJJJJJJJJJJJJJJJJJq#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&YIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJu",' + NL +
    '"SPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ9#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&mIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJK/",' + NL +
    '"NJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJq#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&mIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKK(",' + NL +
    '"iJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJH,#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&jIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKPPE",' + NL +
    '"{IJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLJJJJJJJJJJJJ,.################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&jIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKPIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJQ",' + NL +
    '"RPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJZBMVLJJJJJJJJq#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPZCCZLPIIIIIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJK]",' + NL +
    '"EPJJJJJJJJJJJJJJJJJJJJJJJJJJKJJJJJJJKLLMMMMMMBAJJJJJL,#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&jIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPHCCCCCCCCLPIIIIIIIIIIIIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKK]",' + NL +
    '"EIJJJJJJJJJJJJJJJJJJJJJJJJJJLJJJJJJJLBMMMMMMMMMMZHJJJ>#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&kIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHCCCCCCCCCCCCCLKIIIIIIIIIIIIIIIIIIIIILJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKK]",' + NL +
    '"/JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLVMMMMMMMMMMMMMMVLJO#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPZZCCCCCCCCCCCCCCCCLKIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ ",' + NL +
    '"]JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLVMMMMMMMMMMMMMMMMBMV>#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPLCCCCCCCCCCCCCCCCCCCCCCLKIIIIIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ ",' + NL +
    '"]PJJJJJJJJJJJJJJJJJJJJJJJJJKJJLZMMMMMMMMMMMMMMMMMMMMMO#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPHCCCCCCCCCCCCCCCCCCCCCCCCCCCHKIIIIIIIIIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPN ",' + NL +
    '" JJJJJJJJJJJJJJJJJJJJJJJJJJKLZMMMMMMMMMMMMMMMMMMMMMMMO#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&jUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIKZZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCVAKIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJPi ",' + NL +
    '" TPPJJJJJJJJJJJJJJJJJJJJJJJZMMMMMMMMMMMMMMMMMMMMMMMMMX#################################$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&kIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCZAKIPJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJu ",' + NL +
    '" MJJJJJJJJJJJJJJJJJJJJJJJAMMMMMMMMMMMMMMMMMMMMMMMMMMB##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCZHJHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJE ",' + NL +
    '" RJJJJJJJJJJJJJJJJJKJJJLBMMMMMMMMMMMMMMMMMMMMMMMMMMMM##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIIIIPHZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCZCCZLHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKK/ ",' + NL +
    '" /JJJJJJJJJJJJJJJJJKJLBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIIIPACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCALHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJKP] ",' + NL +
    '" [JJJJJJJJJJJJJJKJJLVMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qIIIIIIIIIIIIIIIIIIIIIIIKACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAAHJLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJL  ",' + NL +
    '" ]JJJJJJJJJJJJJJKLVBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<IPIIIIIIIIIIIIIIIIIIIIHCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJN  ",' + NL +
    '"  PJJJJJJJJJJJJLVMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<HHJKIIIIIIIIIIIIIIIIPZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCZCCAHLJJJJJJJJJJJJJJJJJJJJJJJJJJIi  ",' + NL +
    '"  NFJJJJJJJJJJFVMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&,HHHHHHKPIIIIIIIIIIPACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCZAHJJJJJJJJJJJJJJJJJJJJJJJP/  ",' + NL +
    '"  uJJJJJJJJJLNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<HHAHHHAHHPPIIIIIIHCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAAHLJJJJJJJJJJJJJJJJJJJJ[  ",' + NL +
    '"  /KJJJJJJLBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMl##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<HHHHHHHHHHHHPPIKCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCALJJJJJJJJJJJJJJJJJJ   ",' + NL +
    '"  ]PJJKJLVMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMl##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<HHHAHHHHHHAHHLZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCHHHJJJJJJJJJJJJJJ   ",' + NL +
    '"   LJJLVBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%HHAHHHAAHHHHZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCZZZAHJJJJJJJJJJJR   ",' + NL +
    '"   MLCMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMl##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&HHHHAHHHHHACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAHJJJJJJJJ/   ",' + NL +
    '"   !MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%HHHHHHHHACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAHJJJJJ]   ",' + NL +
    '"   {MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&HHHHHHACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCZAHKJ    ",' + NL +
    '"   ]MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*HAHHAACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAL]   ",' + NL +
    '"    JBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&HHHACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAN    ",' + NL +
    '"    RCMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&FACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAu    ",' + NL +
    '"    EMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC[    ",' + NL +
    '"     NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&VCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC     ",' + NL +
    '"     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAAR     ",' + NL +
    '"     uMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA!     ",' + NL +
    '"     ]MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC]     ",' + NL +
    '"      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp###################################&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$bCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCf      ",' + NL +
    '"      uMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCE      ",' + NL +
    '"      ]MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$mCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA]      ",' + NL +
    '"       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMpX#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&mCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCz       ",' + NL +
    '"       uMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCE       ",' + NL +
    '"       ]MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&kCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA]       ",' + NL +
    '"        fMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCi        ",' + NL +
    '"        QBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&kCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA)        ",' + NL +
    '"         BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%%gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAAC         ",' + NL +
    '"         iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC!         ",' + NL +
    '"         ]MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAA]         ",' + NL +
    '"          zBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&gVZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAi          ",' + NL +
    '"          [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$qMMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA)          ",' + NL +
    '"           MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&9MMMMBZCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCy           ",' + NL +
    '"           /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qMMMMMMNCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA)           ",' + NL +
    '"            BBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&,MMMMMMMMMVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBarraMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC            ",' + NL +
    '"            iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&qMMMMMMMMMMMBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCNawrrrrwwaNCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCE            ",' + NL +
    '"             BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&,MMMMMMMMMMMMMNCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCClrwwwwwwwwwwwrMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAAC             ",' + NL +
    '"             iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9X#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&,MMMMMMMMMMMMMMMMVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCawwwwwwwwwwwwwwwwwaMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCAE             ",' + NL +
    '"              VMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&,MMMMMMMMMMMMMMMMMMBCCCCCCCCCCCCCCCCCCCCCCCCCNawwwwwwwwwwwwwwwwwwwwwraNCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCN              ",' + NL +
    '"              uMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&,MMMMMMMMMMMMMMMMMMMMBCCCCCCCCCCCCCCCCCCCCCMrwwwwwwwwwwwwwwwwwwwwwwwwwwrMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA)              ",' + NL +
    '"               NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<MMMMMMMMMMMMMMMMMMMMMMBCCCCCCCCCCCCCCCCClwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwraNCCCCCCCCCCCCCCCCCCCCCCCCCAAN               ",' + NL +
    '"               {MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&>MMMMMMMMMMMMMMMMMMMMMMMMMCCCCCCCCCCCCBawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwraCCCCCCCCCCCCCCCCCCCCCCCCA)               ",' + NL +
    '"                MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM9##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&>MMMMMMMMMMMMMMMMMMMMMMMMMMMBCCCCCCCMrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaMCCCCCCCCCCCCCCCCCCCCAy                ",' + NL +
    '"                QMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&<MMMMMMMMMMMMMMMMMMMMMMMMMMMMMBCCBMwwrrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwlCCCCCCCCCCCCCCCCCCA`                ",' + NL +
    '"                 NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&>MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMlawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrlCCCCCCCCCCCCCCCu                 ",' + NL +
    '"                 ]BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*MMMMMMMMMMMMMMMMMMMMMMMMMMMllrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaMCCCCCCCCCCCN]                 ",' + NL +
    '"                  iBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*MMMMMMMMMMMMMMMMMMMMMMMMMMlwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrlBCCCCCCCCE                  ",' + NL +
    '"                   BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&lMMMMMMMMMMMMMMMMMMMMMMlrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrwrrMCCCCCf                   ",' + NL +
    '"                   QMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+.#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&MMMMMMMMMMMMMMMMMMMMMlrrrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrwwrlNCC]                   ",' + NL +
    '"                    fMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&MMMMMMMMMMMMMMMMMMMsrrrrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrwwwrrr2]                   ",' + NL +
    '"                     BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM>##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dMMMllMMMMMMMMMMlarwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrl                     ",' + NL +
    '"                     /NBMMMMMMMMMMMMMMMMMMMMMMMMMMMMO##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&lMMlBBMMMMMMMMlarwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwraE                     ",' + NL +
    '"                      fBMMMMMMMMMMMMMMMMMMMMMMMMMMMMO##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dMMMllMMMMMMlrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwi                      ",' + NL +
    '"                       VMMMMMMMMMMMMMMMMMMMMMMMMMMMMO##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dMMMBlMMMMarwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                       ",' + NL +
    '"                       [MMMMMMMMMMMMMMMMMMMMMMMMMMMMO##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dMMMMlMlarwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrr`                       ",' + NL +
    '"                        uMMMMMMMMMMMMMMMMMMMMMMMMMMBO##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&*dMMMMlrrrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrr2                        ",' + NL +
    '"                         MMMMMMMMMMMMMMMMMMMMMMMMMMM>X#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&dlMsrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwt                         ",' + NL +
    '"                         ]BMMMMMMMMMMMMMMMMMMMMMMMMMO##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&darwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrr]                         ",' + NL +
    '"                          [CMMMMMMMMMMMMMMMMMMMMMMMM###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$&awrwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwr)]                         ",' + NL +
    '"                           2MMMMMMMMMMMMMMMMMMMMMMMMX##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$9wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwr{                           ",' + NL +
    '"                            fBMMMMMMMMMMMMMMMMMMMMMMXX#################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&pwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrai                            ",' + NL +
    '"                             NMMMMMMMMMMMMMMMMMMMMMM>##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&prwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrat                             ",' + NL +
    '"                              CBMMMMMMMMMMMMMMMMMMMM###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&prwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwr]                             ",' + NL +
    '"                              ]CMMMMMMMMMMMMMMMMMMMM###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+rwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa]                              ",' + NL +
    '"                               QMBMMMMMMMMMMMMMMMMMM###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$%+wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrl)                               ",' + NL +
    '"                                (BMMMMMMMMMMMMMMMMMM###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&#9wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrE]                               ",' + NL +
    '"                                 uNMMMMMMMMMMMMMMMMM###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwr{                                 ",' + NL +
    '"                                  iMMMMMMMMMMMMMMMMl###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww2                                  ",' + NL +
    '"                                   fNMMMMMMMMMMMMMMc###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwi                                   ",' + NL +
    '"                                    RBMMMMMMMMMMMMMl###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwi                                    ",' + NL +
    '"                                     fMMMMMMMMMMMMMl###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrrry                                     ",' + NL +
    '"                                      yMMMMMMMMMMMMs###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrrri                                      ",' + NL +
    '"                                       fMMMMMMMMMMMd###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrri                                       ",' + NL +
    '"                                        fMMMMMMMMMBd###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$>wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwri                                        ",' + NL +
    '"                                         RMMMMMMMMMs###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&,wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa!                                         ",' + NL +
    '"                                          uNMMMMMMNd#####################.#############$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrE]]                                        ",' + NL +
    '"                                           EACMMMMMs###################################&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&>wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrrs[                                           ",' + NL +
    '"                                            ]BMNMMBs###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&>wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrra[                                            ",' + NL +
    '"                                             ]CCMMMd###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwre]                                             ",' + NL +
    '"                                               fMMMd###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwy                                               ",' + NL +
    '"                                                {MMd###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwr{                                                ",' + NL +
    '"                                                 ]Vd###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwl[                                                 ",' + NL +
    '"                                                  ]M###################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa                                                   ",' + NL +
    '"                                                    1##################################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwr{                                                    ",' + NL +
    '"                                                    ])+$###############################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwra]                                                     ",' + NL +
    '"                                                       p###############################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwy                                                       ",' + NL +
    '"                                                        {,#############################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrwwwwrrrQ                                                        ",' + NL +
    '"                                                          @############################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrwwwwri                                                          ",' + NL +
    '"                                                           E+##########################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrwwrl[                                                           ",' + NL +
    '"                                                             0#########################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrwr2                                                             ",' + NL +
    '"                                                              ]0#######################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwway]                                                              ",' + NL +
    '"                                                                {+#####################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&pwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwt[                                                                ",' + NL +
    '"                                                                  1O###################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$pwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrwrl{                                                                  ",' + NL +
    '"                                                                    {O#################$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrwrr2                                                                    ",' + NL +
    '"                                                                      0,###############$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$pwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwrrri                                                                      ",' + NL +
    '"                                                                        0O#############$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%pwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwry                                                                        ",' + NL +
    '"                                                                          {+###########$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&pwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa2                                                                          ",' + NL +
    '"                                                                            {+#########$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%9wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwlE                                                                            ",' + NL +
    '"                                                                              )pO######$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$9wwwwwwwwwwwwwwwwwwwwwwwwwwrwwwwwwrrrz[                                                                              ",' + NL +
    '"                                                                              ]  {9####&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$%pwwwwwwwwwwwwwwwwwwwwwwwwwwrrwwwwrr2                                                                                 ",' + NL +
    '"                                                                                   [p+#$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&9wwwwwwwwwwwwwwwwwwwwwwwwwwrrrrly`                                                                                   ",' + NL +
    '"                                                                                      [+&*&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&9wwwwwwwwwwwwwwwwwwwwwwwwwwrly[                                                                                      ",' + NL +
    '"                                                                                         E,>&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&%9wwwwwwwwwwwwwwwwwwwwrwrrry[                                                                                         ",' + NL +
    '"                                                                                            ]1>&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$*+wwwwwwwwwwwrwwwwwwwwrt2]                                                                                            ",' + NL +
    '"                                                                                                [@q,=*&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwrrwwwwrrwrrrrrrai`                                                                                                ",' + NL +
    '"                                                                                                    ]{9q>&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+wwrrwwwwrlrrry2]                                                                                                    ",' + NL +
    '"                                                                                                          {@p,%&&&&&&&&&&&&&&&&&&&&&&%&&&&%+wwlrwlaeiE                                                                                                          ",' + NL +
    '"                                                                                                                 {1@p+,,,>>>&>&&&&%%%%%%+++py2E                                                                                                                 "' + NL +
    '};' + NL;

implementation

end.

