// -*- compile-command: "./test_single_testcase.sh TTestCastleInternalOpenTypeFont" -*-
{
  Copyright 2026-2026 Michalis Kamburelis.

  This file is part of "Castle Game Engine".

  "Castle Game Engine" is free software; see the file COPYING.md,
  included in this distribution, for details about the copyright.

  "Castle Game Engine" is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

  ----------------------------------------------------------------------------
}

{ Test CastleInternalOpenTypeFont and CastleInternalGlyphRasterizer units
  (pure Pascal font reading and rendering, used when CASTLE_FREETYPE_PASCAL
  is defined). }
unit TestCastleInternalOpenTypeFont;

{$I ../../../src/common_includes/castleconf.inc}

interface

uses Classes, SysUtils,
  CastleTester, CastleInternalOpenTypeFont;

type
  TTestCastleInternalOpenTypeFont = class(TCastleTestCase)
  strict private
    { Check glyph for character C.
      Expected values were calculated by a reference implementation
      of the same algorithm. }
    procedure CheckGlyph(const Font: TOpenTypeFont; const C: Char;
      const ExpectedGlyph, ExpectedAdvance, ExpectedCommands: Integer;
      const PixelSize: Integer; const Mono: Boolean;
      const ExpectedWidth, ExpectedHeight, ExpectedLeft, ExpectedTop,
      ExpectedPitch, ExpectedSum: Integer);
    { Font data truncated or corrupted may cause only EOpenTypeFontError
      or EReadError. }
    procedure CheckRobustness(const Url: String);
  published
    { Test font with TrueType outlines. }
    procedure TestTrueType;
    { Test real-world font with CFF outlines (Type 2 charstrings). }
    procedure TestCff;
    { Test font with CFF outlines generated by castle_test_cff_generate.py,
      that uses many Type 2 charstring operators. }
    procedure TestCffGenerated;
    procedure TestInvalid;
    procedure TestRobustness;
  end;

implementation

uses CastleDownload, CastleInternalGlyphRasterizer;

procedure TTestCastleInternalOpenTypeFont.CheckGlyph(const Font: TOpenTypeFont;
  const C: Char; const ExpectedGlyph, ExpectedAdvance, ExpectedCommands: Integer;
  const PixelSize: Integer; const Mono: Boolean;
  const ExpectedWidth, ExpectedHeight, ExpectedLeft, ExpectedTop,
  ExpectedPitch, ExpectedSum: Integer);

  function CountBits(B: Byte): Integer;
  begin
    Result := 0;
    while B <> 0 do
    begin
      Result := Result + (B and 1);
      B := B shr 1;
    end;
  end;

var
  Glyph, I, Sum: Integer;
  Outline: TGlyphOutline;
  Rasterized: TRasterizedGlyph;
begin
  Glyph := Font.GlyphIndex(Ord(C));
  AssertEquals(ExpectedGlyph, Glyph);
  AssertEquals(ExpectedAdvance, Font.AdvanceWidth(Glyph));

  Outline := TGlyphOutline.Create;
  try
    Font.GetGlyphOutline(Glyph, Outline);
    AssertEquals(ExpectedCommands, Outline.Count);

    RasterizeGlyph(Outline, PixelSize / Font.UnitsPerEm, 0, 0, Mono, Rasterized);
    AssertEquals(ExpectedWidth, Rasterized.Width);
    AssertEquals(ExpectedHeight, Rasterized.Height);
    AssertEquals(ExpectedLeft, Rasterized.Left);
    AssertEquals(ExpectedTop, Rasterized.Top);
    AssertEquals(ExpectedPitch, Rasterized.Pitch);
    AssertEquals(Mono, Rasterized.Mono);
    AssertEquals(Int64(ExpectedPitch * ExpectedHeight), Int64(Length(Rasterized.Data)));

    Sum := 0;
    for I := 0 to Length(Rasterized.Data) - 1 do
      if Mono then
        Sum := Sum + CountBits(Rasterized.Data[I])
      else
        Sum := Sum + Rasterized.Data[I];
    { Allow small differences, as floating-point calculations may differ
      a bit between compilers and platforms. }
    AssertTrue(Format('Glyph "%s" pixels sum %d, expected %d', [C, Sum, ExpectedSum]),
      Abs(Sum - ExpectedSum) <= ExpectedSum div 50 + 2);
  finally FreeAndNil(Outline) end;
end;

procedure TTestCastleInternalOpenTypeFont.TestTrueType;
var
  Font: TOpenTypeFont;
begin
  { TOpenTypeFont owns the stream }
  Font := TOpenTypeFont.Create(
    Download('castle-data:/fonts/PARPG.ttf', [soForceMemoryStream]) as TCustomMemoryStream);
  try
    AssertEquals(1, Font.NumFaces);
    AssertEquals(176, Font.NumGlyphs);
    AssertEquals(1024, Font.UnitsPerEm);
    AssertEquals('Fixed', String(Font.FamilyName));
    AssertEquals('Regular', String(Font.StyleName));
    AssertFalse(Font.Bold);
    AssertFalse(Font.Italic);
    AssertFalse(Font.HasKerning);
    AssertEquals(1224, Font.Ascender);
    AssertEquals(-107, Font.Descender);
    AssertEquals(92, Font.LineGap);

    CheckGlyph(Font, 'A', 33, 734, 91, 32, false, 21, 27, 6, 31, 21, 40758);
    CheckGlyph(Font, 'A', 33, 734, 91, 32, true, 19, 26, 7, 31, 4, 166);
    CheckGlyph(Font, 'g', 71, 734, 149, 32, false, 20, 26, 7, 24, 20, 45171);
    CheckGlyph(Font, 'g', 71, 734, 149, 32, true, 20, 25, 7, 24, 4, 176);
    { space is not mapped in this font, so it gives glyph 0 (empty) }
    CheckGlyph(Font, ' ', 0, 734, 0, 32, false, 0, 0, 0, 0, 0, 0);
  finally FreeAndNil(Font) end;
end;

procedure TTestCastleInternalOpenTypeFont.TestCff;
var
  Font: TOpenTypeFont;
begin
  { TOpenTypeFont owns the stream }
  Font := TOpenTypeFont.Create(
    Download('castle-data:/fonts/Urbanist-Regular.otf', [soForceMemoryStream]) as TCustomMemoryStream);
  try
    AssertEquals(1, Font.NumFaces);
    AssertEquals(535, Font.NumGlyphs);
    AssertEquals(2000, Font.UnitsPerEm);
    AssertEquals('Urbanist', String(Font.FamilyName));
    AssertEquals('Regular', String(Font.StyleName));
    AssertFalse(Font.Bold);
    AssertFalse(Font.Italic);
    AssertFalse(Font.HasKerning);
    AssertEquals(1900, Font.Ascender);
    AssertEquals(-500, Font.Descender);
    AssertEquals(0, Font.LineGap);

    CheckGlyph(Font, 'A', 1, 1353, 11, 32, false, 20, 23, 1, 23, 20, 32364);
    CheckGlyph(Font, 'A', 1, 1353, 11, 32, true, 19, 22, 1, 22, 4, 123);
    CheckGlyph(Font, 'g', 223, 1175, 18, 32, false, 17, 25, 0, 17, 17, 40527);
    CheckGlyph(Font, 'g', 223, 1175, 18, 32, true, 16, 24, 1, 16, 2, 159);
    CheckGlyph(Font, ' ', 400, 480, 0, 32, false, 0, 0, 0, 0, 0, 0);
  finally FreeAndNil(Font) end;
end;

procedure TTestCastleInternalOpenTypeFont.TestCffGenerated;
var
  Font: TOpenTypeFont;
begin
  { TOpenTypeFont owns the stream }
  Font := TOpenTypeFont.Create(
    Download('castle-data:/fonts/castle_test_cff.otf', [soForceMemoryStream]) as TCustomMemoryStream);
  try
    AssertEquals(1, Font.NumFaces);
    AssertEquals(11, Font.NumGlyphs);
    AssertEquals(1000, Font.UnitsPerEm);
    AssertEquals('Castle Test CFF', String(Font.FamilyName));
    AssertEquals('Regular', String(Font.StyleName));
    AssertFalse(Font.Bold);
    AssertFalse(Font.Italic);
    AssertFalse(Font.HasKerning);
    AssertEquals(800, Font.Ascender);
    AssertEquals(-200, Font.Descender);
    AssertEquals(0, Font.LineGap);

    { See castle_test_cff_generate.py for what each glyph tests. }
    CheckGlyph(Font, ' ', 1, 250, 0, 32, false, 0, 0, 0, 0, 0, 0);
    CheckGlyph(Font, 'A', 2, 650, 13, 32, false, 27, 20, 1, 21, 27, 46989);
    CheckGlyph(Font, 'A', 2, 650, 13, 32, true, 26, 19, 2, 21, 4, 192);
    CheckGlyph(Font, 'B', 3, 500, 8, 32, false, 13, 15, -1, 15, 13, 33160);
    CheckGlyph(Font, 'B', 3, 500, 8, 32, true, 11, 14, 0, 14, 2, 129);
    CheckGlyph(Font, 'C', 4, 700, 8, 32, false, 22, 22, -2, 22, 22, 52830);
    CheckGlyph(Font, 'C', 4, 700, 8, 32, true, 21, 22, -2, 22, 4, 207);
    CheckGlyph(Font, 'D', 5, 500, 8, 32, false, 14, 18, 1, 18, 14, 41261);
    CheckGlyph(Font, 'D', 5, 500, 8, 32, true, 12, 18, 2, 18, 2, 160);
    CheckGlyph(Font, 'E', 6, 800, 15, 32, false, 22, 16, 1, 17, 22, 9226);
    CheckGlyph(Font, 'E', 6, 800, 15, 32, true, 20, 15, 2, 16, 4, 50);
    CheckGlyph(Font, 'F', 7, 500, 4, 32, false, 7, 7, 3, 10, 7, 10409);
    CheckGlyph(Font, 'F', 7, 500, 4, 32, true, 7, 7, 3, 10, 2, 49);
    CheckGlyph(Font, 'G', 8, 550, 9, 32, false, 10, 20, 3, 20, 10, 47295);
    CheckGlyph(Font, 'G', 8, 550, 9, 32, true, 10, 19, 3, 19, 2, 190);
    CheckGlyph(Font, 'H', 9, 500, 5, 32, false, 11, 20, 1, 20, 11, 47226);
    CheckGlyph(Font, 'H', 9, 500, 5, 32, true, 9, 19, 2, 20, 2, 171);
    CheckGlyph(Font, 'I', 10, 500, 7, 32, false, 10, 14, 3, 15, 10, 31348);
    CheckGlyph(Font, 'I', 10, 500, 7, 32, true, 10, 12, 3, 14, 2, 120);
  finally FreeAndNil(Font) end;
end;

procedure TTestCastleInternalOpenTypeFont.TestInvalid;

  { Assert that font data in Stream is invalid.
    Stream becomes owned by this routine (like by TOpenTypeFont.Create). }
  procedure AssertInvalid(const Stream: TCustomMemoryStream);
  var
    Font: TOpenTypeFont;
  begin
    try
      Font := TOpenTypeFont.Create(Stream);
      FreeAndNil(Font);
      Fail('Invalid font data should raise EOpenTypeFontError or EReadError');
    except
      on EOpenTypeFontError do ; // expected for invalid data
      on EReadError do ; // expected for truncated data
    end;
  end;

  function GarbageStream(const Size: Integer): TMemoryStream;
  var
    I: Integer;
    B: Byte;
  begin
    Result := TMemoryStream.Create;
    for I := 0 to Size - 1 do
    begin
      B := I;
      Result.WriteBuffer(B, 1);
    end;
  end;

var
  Data: TStream;
  Truncated: TMemoryStream;
begin
  AssertInvalid(GarbageStream(100));
  AssertInvalid(GarbageStream(4)); // too small

  Data := Download('castle-data:/fonts/PARPG.ttf', [soForceMemoryStream]);
  try
    Truncated := TMemoryStream.Create;
    Truncated.CopyFrom(Data, 200);
  finally FreeAndNil(Data) end;
  AssertInvalid(Truncated);
end;

procedure TTestCastleInternalOpenTypeFont.CheckRobustness(const Url: String);
const
  TestChars = 'AgQ@';
var
  Original: TStream;
  Corrupted: TMemoryStream;
  Font: TOpenTypeFont;
  Outline: TGlyphOutline;
  Rasterized: TRasterizedGlyph;
  Iteration, I, Size: Integer;
  Bytes: PByte;
begin
  RandSeed := 12345;
  Original := Download(Url, [soForceMemoryStream]);
  Outline := TGlyphOutline.Create;
  try
    for Iteration := 0 to 199 do
    begin
      { make truncated or corrupted copy of the font }
      Corrupted := TMemoryStream.Create;
      Corrupted.CopyFrom(Original, 0);
      if Iteration < 50 then
      begin
        Size := 12 + Random(Integer(Original.Size) - 12);
        Corrupted.Size := Size;
      end else
      begin
        Size := Integer(Original.Size);
        Bytes := PByte(Corrupted.Memory);
        for I := 0 to Random(40) do
          Bytes[Random(Size)] := Random(256);
      end;

      try
        { TOpenTypeFont owns Corrupted (also when constructor fails) }
        Font := TOpenTypeFont.Create(Corrupted);
        try
          for I := 1 to Length(TestChars) do
          begin
            Font.GetGlyphOutline(Font.GlyphIndex(Ord(TestChars[I])), Outline);
            RasterizeGlyph(Outline, 32 / Font.UnitsPerEm, 0, 0, false, Rasterized);
            RasterizeGlyph(Outline, 32 / Font.UnitsPerEm, 0, 0, true, Rasterized);
          end;
        finally FreeAndNil(Font) end;
      except
        on EOpenTypeFontError do ; // expected for invalid data
        on EReadError do ; // expected for truncated data
      end;
    end;
  finally
    FreeAndNil(Outline);
    FreeAndNil(Original);
  end;
end;

procedure TTestCastleInternalOpenTypeFont.TestRobustness;
begin
  CheckRobustness('castle-data:/fonts/PARPG.ttf');
  CheckRobustness('castle-data:/fonts/Urbanist-Regular.otf');
  CheckRobustness('castle-data:/fonts/castle_test_cff.otf');
end;

initialization
  RegisterTest(TTestCastleInternalOpenTypeFont);
end.
