unit AllKambiBaseUnits;

{ This is automatically generated unit, useful to compile all units
  in this directory (and OS-specific subdirectories like
  unix/, linux/, and windows/).
  Don't edit.
  Don't use this unit in your programs, it's just not for this.
  Generated by Kambi's Elisp function all-units-in-dir. }

interface

uses
  areas,
  dataerrors,
  enumeratefiles,
  intrects,
  kambiclassutils,
  kambidynlib,
  kambifilesutils,
  kambiinterfaces,
  kambilog,
  kambistringutils,
  kambitimeutils,
  kambiutils,
  kambixmlcfg,
  kambixmlread,
  kambixmlutils,
  kambizlib,
  kambizstream,
  mathexpr,
  kambiscriptlexer,
  kambiscriptparser,
  parseparametersunit,
  progressconsole,
  progressunit,
  rects,
  vectormath
  ;

implementation

end.
