# ----------------------------------------------------------------------------
# GitHub Action workflow to release CGE build on GitHub.
#
# We call other workflows, this seems easiest way to wait for *all* other
# workflows and be able to get their artifacts.
# ----------------------------------------------------------------------------

name: Minimal Pack + Release on Linux + Windows
on:
  pull_request:
  # Run on push to any branch, not on tags.
  # Checking tags is not useful for us (we check the commit when it happened
  # at branch) and we would waste a lot of time on every "snapshpt" tag change.
  push:
    branches:
      - '**'

env:
  # To which GitHub release tag should we upload artifacts.
  # Can be "snapshot" or "vX.Y.Z" (latter when we make stable release).
  release_tag: snapshot
  #release_tag: v7.0-alpha.3

defaults:
  run:
    shell: bash

jobs:
  test_and_pack_docker:
    uses: ./.github/workflows/test-and-pack-docker.yml
  test_and_pack_runner_native:
    uses: ./.github/workflows/test-and-pack-runner-native.yml

  release:
    name: Release
    needs: [
      test_and_pack_docker,
      test_and_pack_runner_native
    ]
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:

    # We can get artifacts from other workflows here, because we called them.
    #
    # History:
    # Note that by default you cannot share artifacts between workflows.
    # See
    # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#sharing-data-between-workflow-runs
    # Solutions:
    # - best, official https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories
    # - alt: https://github.com/dawidd6/action-download-artifact
    # - other, including download using cli: https://stackoverflow.com/questions/60355925/share-artifacts-between-workflows-github-actions

    - name: Download packaged releases
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: List downloaded files
      run: ls -R

    # We use automatic GITHUB_TOKEN secret provided by GitHub with GH CLI, see
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    # https://docs.github.com/en/github-cli/github-cli/about-github-cli

    - name: GH CLI status
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh auth status
    - name: GH CLI test
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release list --repo ${{ github.repository }}

    # Releases files in the GitHub release.
    - name: Release Artifacts
      run: gh release --repo ${{ github.repository }} upload ${{ env.release_tag }} --clobber castle-engine*.zip castle-engine-setup-*.exe
      env:
        GH_TOKEN: ${{ github.token }}

