{ This is an autogenerated unit using gobject introspection (gir2pascal). Do not Edit. }
unit CastleInternalFreetype2_2;

{$MODE OBJFPC}{$H+}

{$PACKRECORDS C}
{$MODESWITCH DUPLICATELOCALS+}

{$ifdef Unix}
{$endif}
{$WARN 3031 off : Values in enumeration types have to be ascending}
interface
uses
  CTypes;

const
  {$ifdef MsWindows}
  Lazfreetype2_2_library = '.dll';
  {$else}
  Lazfreetype2_2_library = '';
  {$endif}

type


  { TFT_Bitmap }
  PPFT_Bitmap = ^PFT_Bitmap;
  PFT_Bitmap = ^TFT_Bitmap;

  TFT_Bitmap = record
  end;




  { TFT_Face }
  PPFT_Face = ^PFT_Face;
  PFT_Face = ^TFT_Face;

  TFT_Face = record
  end;




  { TFT_Library }
  PPFT_Library = ^PFT_Library;
  PFT_Library = ^TFT_Library;

  TFT_Library = record
  end;




  { TFT_Int32 }
  PPFT_Int32 = ^PFT_Int32;
  PFT_Int32 = ^TFT_Int32;
  TFT_Int32 = cint32;

procedure FT_Library_Version; cdecl; external Lazfreetype2_2_library name 'FT_Library_Version';
implementation
end.
